//! Implements the subscription and notification functionality (there's not actually any explicit
//! publication).
//!
//! At heart this is pretty simple, just a bunch of hashmaps/sets for linking subscription ids
//! to tables/keys/singletons. The complicating factor is making it all typed, so we have to interact
//! with the macros in the schema module.
//!
//! Notifiable events are collected as part of committing a transaction, these are then fed back
//! here via macro-generated code to be grouped appropriately, associated with subscribers, and
//! converted into the public-facing form of notifications (an enum generated by the schema macros,
//! which has to be treated generically here).
//!
//! As with other code, many things here are public where they should only be used by the macro-
//! generated code (marked `doc(hidden)`).

use std::{
    any::{Any, TypeId},
    collections::{HashMap, HashSet},
    convert::Infallible,
    fmt,
    hash::Hash,
    marker::PhantomData,
    num::NonZeroUsize,
    sync::{Arc, Mutex, atomic::AtomicUsize},
};

use crate::{
    Error, Owner, Result,
    schema::{GeneratedStorage, Singleton, TableDesc},
    storage::{SinValue, Storage},
};

/// Identifies a subscriber.
///
/// Users should not rely on the `Debug` implementation to identify a subscriber.
#[derive(Debug, Clone, Copy, Eq, PartialEq, Hash)]
pub struct Subscriber(NonZeroUsize);

/// Identifies a subscription.
///
/// Users should not rely on the `Debug` implementation to identify a subscription.
#[derive(Debug, Clone, Copy, Eq, PartialEq, Hash)]
pub struct Subscription(NonZeroUsize, Subscriber);

/// A collection of notifications (mapped from a [`Subscription`]) for a notifier to distribute to
/// subscribers.
#[derive(Clone)]
pub struct Notifications<Notification: Clone>(HashMap<Subscription, Vec<Notification>>);

impl<Notification: Clone> Notifications<Notification> {
    fn single(n: Notification, s: Subscription) -> Self {
        Self([(s, vec![n])].into())
    }
}

impl<Notification: Clone> From<Notifications<Notification>>
    for HashMap<Subscription, Vec<Notification>>
{
    fn from(v: Notifications<Notification>) -> HashMap<Subscription, Vec<Notification>> {
        v.0
    }
}

impl<Notification: Clone> Default for Notifications<Notification> {
    fn default() -> Self {
        Self(HashMap::new())
    }
}

/// A single event within a notification.
#[non_exhaustive]
pub enum Event<D, K: Clone, V: Clone> {
    /// The table has been cleared.
    TableClear,
    /// Mutations to a table where the table has gone from empty to non-empty or the
    /// subscriber is watching the whole table.
    TableUpsert(Vec<K>),
    /// Removes where the subscriber is watching the whole table.
    TableRemove(Vec<K>),
    /// A single key/value is mutated.
    KeyUpsert(K, V),
    /// A key is removed.
    KeyRemove(K),
    // Need to put `PhantomData<D>` somewhere.
    #[doc(hidden)]
    __Nope(PhantomData<D>, Infallible),
}

/// A single event within a notification.
#[non_exhaustive]
pub enum SingletonEvent<D, V: Clone> {
    /// The singleton has been mutated.
    Upsert(V),
    /// A value has been removed from a singleton.
    Remove,
    // Need to put `PhantomData<D>` somewhere.
    #[doc(hidden)]
    __Nope(PhantomData<D>, Infallible),
}

impl<D: TableDesc, K: Clone + fmt::Debug, V: Clone> fmt::Debug for Event<D, K, V> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::TableClear => write!(f, "TableClear({})", D::NAME),
            Self::TableUpsert(_) => write!(f, "TableUpsert({})", D::NAME),
            Self::TableRemove(_) => write!(f, "TableRemove({})", D::NAME),
            Self::KeyUpsert(k, _) => write!(f, "KeyUpsert({}, {k:?})", D::NAME),
            Self::KeyRemove(k) => write!(f, "KeyRemove({}, {k:?})", D::NAME),
            Self::__Nope(..) => unreachable!(),
        }
    }
}

impl<D, K: Clone, V: Clone> Clone for Event<D, K, V> {
    fn clone(&self) -> Self {
        match self {
            Self::TableClear => Self::TableClear,
            Self::TableUpsert(arg0) => Self::TableUpsert(arg0.clone()),
            Self::TableRemove(arg0) => Self::TableRemove(arg0.clone()),
            Self::KeyUpsert(arg0, arg1) => Self::KeyUpsert(arg0.clone(), arg1.clone()),
            Self::KeyRemove(arg0) => Self::KeyRemove(arg0.clone()),
            Self::__Nope(..) => unreachable!(),
        }
    }
}

impl<D, K: Clone + PartialEq, V: Clone + PartialEq> PartialEq for Event<D, K, V> {
    fn eq(&self, other: &Self) -> bool {
        match (self, other) {
            (Self::TableClear, Self::TableClear) => true,
            (Self::TableUpsert(l0), Self::TableUpsert(r0)) => l0 == r0,
            (Self::TableRemove(l0), Self::TableRemove(r0)) => l0 == r0,
            (Self::KeyUpsert(l0, l1), Self::KeyUpsert(r0, r1)) => l0 == r0 && l1 == r1,
            (Self::KeyRemove(l0), Self::KeyRemove(r0)) => l0 == r0,
            (Self::__Nope(..), _) | (_, Self::__Nope(..)) => unreachable!(),
            _ => false,
        }
    }
}
impl<D, K: Clone + PartialEq, V: Clone + PartialEq> Eq for Event<D, K, V> {}

impl<D: crate::schema::Singleton, V: Clone> fmt::Debug for SingletonEvent<D, V> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Upsert(_) => write!(f, "Upsert({})", std::any::type_name::<D>()),
            Self::Remove => write!(f, "Remove({})", std::any::type_name::<D>()),
            Self::__Nope(..) => unreachable!(),
        }
    }
}

impl<D, V: Clone> Clone for SingletonEvent<D, V> {
    fn clone(&self) -> Self {
        match self {
            Self::Upsert(arg0) => Self::Upsert(arg0.clone()),
            Self::Remove => Self::Remove,
            Self::__Nope(..) => unreachable!(),
        }
    }
}

impl<D, V: Clone + PartialEq> PartialEq for SingletonEvent<D, V> {
    fn eq(&self, other: &Self) -> bool {
        match (self, other) {
            (Self::Upsert(l0), Self::Upsert(r0)) => l0 == r0,
            (Self::Remove, Self::Remove) => true,
            (Self::__Nope(..), _) | (_, Self::__Nope(..)) => unreachable!(),
            _ => false,
        }
    }
}

impl<D, V: Clone + PartialEq> Eq for SingletonEvent<D, V> {}

/// An object which forwards notifications from the store to subscribers.
pub trait Notifier: Send + Sync + std::fmt::Debug + 'static {
    /// The store's notification enum.
    type Notification: Clone;

    /// Notify subscribers.
    ///
    /// `notifications` contains all notifications for all subscribers for a single transaction. There
    /// is no grouping by subscriber.
    ///
    /// Implementers must not call back into the store because a read lock is held while this method
    /// is called.
    ///
    /// If possible, implementers should not block while sending these notifications. If sending is
    /// possible to block, or take significant time, Notifications should be queued and sent asynchronously.
    fn notify(&self, notifications: Notifications<Self::Notification>);
}

/// A notifier which does no notification, calls to `notify` do nothing.
pub struct NoOpNotifier<T: Send>(std::marker::PhantomData<T>);

impl<T: Clone + Send + Sync + 'static> std::fmt::Debug for NoOpNotifier<T> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_tuple("NoOpNotifier").finish()
    }
}

impl<T: Clone + Send + Sync + 'static> NoOpNotifier<T> {
    /// Create a new `NoOpNotifier` as a `Notifier` trait object.
    #[allow(clippy::new_ret_no_self)]
    pub fn new() -> Arc<dyn Notifier<Notification = T>> {
        Arc::new(Self(std::marker::PhantomData))
    }
}

impl<T: Clone + Send + Sync + 'static> Notifier for NoOpNotifier<T> {
    type Notification = T;

    fn notify(&self, _: Notifications<T>) {}
}

/// Internal storage of subscription metadata.
#[doc(hidden)]
#[derive(Debug)]
pub struct Subscriptions<Notif: Clone> {
    /// The most recently issued subscriber id.
    cur_subscriber_id: AtomicUsize,
    /// The most recently issued subscription id.
    cur_subscription_id: AtomicUsize,

    /// A record of subscribers and their associated owners.
    subscribers: Mutex<HashMap<Subscriber, Owner>>,
    /// Subscriptions to each singleton KV pair.
    singletons: Mutex<HashMap<TypeId, HashSet<Subscription>>>,
    /// Subscriptions to the whole store.
    all: Mutex<HashSet<Subscription>>,
    /// Subscription metadata for each table.
    tables: Mutex<HashMap<TypeId, Box<dyn Any + Send>>>,

    notifier: Arc<dyn Notifier<Notification = Notif>>,
}

impl<Notif: Clone + 'static> Subscriptions<Notif> {
    pub(crate) fn new(notifier: Arc<dyn Notifier<Notification = Notif>>) -> Self {
        Subscriptions {
            cur_subscriber_id: Default::default(),
            cur_subscription_id: Default::default(),
            subscribers: Default::default(),
            singletons: Default::default(),
            all: Default::default(),
            tables: Default::default(),
            notifier,
        }
    }

    /// Sends `notifications` to subscribers. Call after a successful commit.
    pub(crate) fn on_commit(&self, notifications: Notifications<Notif>) {
        self.notifier.notify(notifications);
    }

    /// Whether there are subscribers to the table `D`.
    ///
    /// May be an over-approximation (i.e., there may be false positives but not false
    /// negatives, as long as the global lock on the store is held).
    pub fn has_subscribers<D: TableDesc>(&self) -> bool {
        if !self.all.lock().unwrap().is_empty() {
            return true;
        }

        let tables = self.tables.lock().unwrap();
        let Some(table) = tables.get(&TypeId::of::<D>()) else {
            return false;
        };
        let table: &TableSubscriptions<D::Key> = table.downcast_ref().unwrap();

        !table.subscriptions_all.is_empty() || !table.subscriptions.is_empty()
    }

    /// Process events for `D` and add to `notifications`.
    pub fn collect_events<D: TableDesc>(
        &self,
        notifications: &mut Notifications<NotificationType<D>>,
        events: HashMap<D::Key, WatchedEvent<D::NotificationValue>>,
    ) {
        let all = self.all.lock().unwrap();
        let all_events = process_events::<D>(&events, None);
        for s in all.iter() {
            notifications.append_notifications(*s, &all_events);
        }

        let tables = self.tables.lock().unwrap();
        let Some(table) = tables.get(&TypeId::of::<D>()) else {
            return;
        };
        let table: &TableSubscriptions<D::Key> = table.downcast_ref().unwrap();

        for s in &table.subscriptions_all {
            notifications.append_notifications(*s, &all_events);
        }

        for (k, s) in table.subscriptions.iter() {
            let events = process_events::<D>(&events, Some(k.clone()));
            if !events.is_empty() {
                for s in s {
                    notifications.append_notifications(*s, &events);
                }
            }
        }
    }

    /// Whether there are subscribers to the singleton `S`.
    ///
    /// May in theory be an over-approximation (i.e., there may be false positives but not false
    /// negatives, as long as the global lock on the store is held). However, the current
    /// implementation is precise.
    pub fn has_singleton_subscribers<S: Singleton>(&self) -> bool {
        if !self.all.lock().unwrap().is_empty() {
            return true;
        }

        let singletons = self.singletons.lock().unwrap();
        let Some(subs) = singletons.get(&TypeId::of::<S>()) else {
            return false;
        };

        !subs.is_empty()
    }

    /// Process events for singleton `S` into notifications and add them to `notifications`.
    pub fn collect_singleton_events<S: Singleton>(
        &self,
        notifications: &mut Notifications<
            <S::Storage as crate::schema::GeneratedStorage>::Notification,
        >,
        event: &SinValue,
    ) {
        let notification = match event {
            SinValue::None => S::make_notification(SingletonEvent::Remove),
            v => S::make_notification(SingletonEvent::Upsert(S::from_value_clone(v))),
        };

        for s in self.all.lock().unwrap().iter() {
            notifications.append_notifications(*s, std::slice::from_ref(&notification));
        }

        let singletons = self.singletons.lock().unwrap();
        if let Some(subs) = singletons.get(&TypeId::of::<S>()) {
            for s in subs {
                notifications.append_notifications(*s, std::slice::from_ref(&notification));
            }
        }
    }

    /// Create and remember a new subscriber ID.
    pub(crate) fn register_subscriber(&self, owner: Owner) -> Subscriber {
        let id = self
            .cur_subscriber_id
            .fetch_add(1, std::sync::atomic::Ordering::Relaxed);
        let result = Subscriber(NonZeroUsize::new(id + 1).unwrap());
        self.subscribers.lock().unwrap().insert(result, owner);
        result
    }

    /// Create and remember a new subscription ID.
    ///
    /// Does not subscribe to anything.
    fn register_subscription(&self, subscriber: Subscriber) -> Result<Subscription> {
        self.subscribers
            .lock()
            .unwrap()
            .get(&subscriber)
            .ok_or(Error::UnknownSubscriber)?;
        let id = self
            .cur_subscription_id
            .fetch_add(1, std::sync::atomic::Ordering::Relaxed);
        Ok(Subscription(NonZeroUsize::new(id + 1).unwrap(), subscriber))
    }

    /// Associate a subscription ID with a singleton KV pair.
    pub(crate) fn create_singleton_subscription<S: Singleton>(
        &self,
        subscriber: Subscriber,
    ) -> Result<Subscription> {
        let subscription = self.register_subscription(subscriber)?;
        let mut singletons = self.singletons.lock().unwrap();
        singletons
            .entry(TypeId::of::<S>())
            .or_default()
            .insert(subscription);
        Ok(subscription)
    }

    /// Remove a subscription ID from watching a singleton KV pair.
    pub(crate) fn remove_singleton_subscription<S: Singleton>(&self, subscription: Subscription) {
        let mut singletons = self.singletons.lock().unwrap();
        let Some(subs) = singletons.get_mut(&TypeId::of::<S>()) else {
            return;
        };

        subs.retain(|s| s != &subscription);
    }

    /// Associate a subscription ID with a global watch, i.e., subscribed to all keys and tables in the store.
    pub(crate) fn create_global_subscription(
        &self,
        subscriber: Subscriber,
    ) -> Result<Subscription> {
        let subscription = self.register_subscription(subscriber)?;
        let mut all = self.all.lock().unwrap();
        all.insert(subscription);
        Ok(subscription)
    }

    /// Remove a global subscription.
    pub(crate) fn remove_global_subscription(&self, subscription: Subscription) {
        let mut all = self.all.lock().unwrap();
        all.retain(|s| s != &subscription);
    }

    /// Associate a subscription ID with a table (watching all keys).
    pub(crate) fn create_table_subscription<D: TableDesc>(
        &self,
        key: D::Key,
        subscriber: Subscriber,
    ) -> Result<Subscription>
    where
        D::Key: Send,
    {
        let subscription = self.register_subscription(subscriber)?;
        let mut tables = self.tables.lock().unwrap();
        tables
            .entry(TypeId::of::<D>())
            .or_insert_with(|| Box::new(TableSubscriptions::<D::Key>::default()))
            .downcast_mut::<TableSubscriptions<D::Key>>()
            .unwrap()
            .subscriptions
            .entry(key)
            .or_default()
            .insert(subscription);
        Ok(subscription)
    }

    /// Associate a subscription ID with a table (watching a single keys).
    pub(crate) fn create_table_subscription_all<D: TableDesc>(
        &self,
        subscriber: Subscriber,
    ) -> Result<Subscription>
    where
        D::Key: Send,
    {
        let subscription = self.register_subscription(subscriber)?;
        let mut tables = self.tables.lock().unwrap();
        tables
            .entry(TypeId::of::<D>())
            .or_insert_with(|| Box::new(TableSubscriptions::<D::Key>::default()))
            .downcast_mut::<TableSubscriptions<D::Key>>()
            .unwrap()
            .subscriptions_all
            .insert(subscription);
        Ok(subscription)
    }

    /// Remove all subscriptions from a specific table (single-key and whole-table subscriptions).
    pub(crate) fn remove_table_subscription<D: TableDesc>(&self, subscription: Subscription) {
        let mut tables = self.tables.lock().unwrap();
        let Some(subs) = tables.get_mut(&TypeId::of::<D>()) else {
            return;
        };

        let subs = subs.downcast_mut::<TableSubscriptions<D::Key>>().unwrap();
        subs.subscriptions_all.retain(|s| s != &subscription);
        subs.subscriptions
            .iter_mut()
            .for_each(|(_, s)| s.retain(|s| s != &subscription));
    }
}

/// Send a notification for the current value of `key` to `subscription`.
pub(crate) fn send_current<D: TableDesc>(
    subs: &Subscriptions<<D::Storage as GeneratedStorage>::Notification>,
    storage: &Storage<D::Storage>,
    key: D::Key,
    subscription: Subscription,
) {
    let table = D::get_table(&storage.tables);
    let Some(value) = table.get(&key, storage.txn_id()) else {
        return;
    };
    let value = D::clone_value_for_notification(value);
    let notification = D::make_notification(Event::KeyUpsert(key, value));
    subs.notifier
        .notify(Notifications::<_>::single(notification, subscription));
}

/// Send a notification for the current value of a singleton to `subscription`.
pub(crate) fn send_current_singleton<S: Singleton>(
    subs: &Subscriptions<<S::Storage as GeneratedStorage>::Notification>,
    storage: &Storage<S::Storage>,
    subscription: Subscription,
) {
    let Some(value) = storage.get_singleton_notification_value::<S>(storage.txn_id()) else {
        return;
    };
    let notification = S::make_notification(SingletonEvent::Upsert(value));
    subs.notifier
        .notify(Notifications::<_>::single(notification, subscription));
}

/// Internal storage of subscription metadata specific to a single table with key of type `K`.
#[derive(Debug)]
pub(crate) struct TableSubscriptions<K: Hash + Eq> {
    /// Subscribed to one key.
    subscriptions: HashMap<K, HashSet<Subscription>>,
    /// Subscribed to all keys.
    subscriptions_all: HashSet<Subscription>,
}

impl<K: Hash + Eq> Default for TableSubscriptions<K> {
    fn default() -> Self {
        Self {
            subscriptions: Default::default(),
            subscriptions_all: Default::default(),
        }
    }
}

/// An internal representation of a notifiable event and possibly the resulting value.
#[doc(hidden)]
#[derive(Clone)]
pub enum WatchedEvent<V: Clone> {
    /// Mutate or insert a single key/value.
    Upsert(V),
    /// A (likely to be bulk) insert into the table.
    KeyOnlyUpsert,
    /// Remove a single key.
    Remove,
    /// Whole table has been cleared.
    Clear,
}

impl<N: Clone> Notifications<N> {
    fn append_notifications(&mut self, subscription: Subscription, notifications: &[N]) {
        self.0
            .entry(subscription)
            .or_default()
            .extend(notifications.iter().cloned());
    }
}

/// Process events for a table (described by `D`) into notifications by collecting internal events
/// into the public event type and wrapping it in the table's notification type.
///
/// `filter` is used when a subscriber is just watching a single key in the table, not all of them.
fn process_events<D: TableDesc>(
    events: &HashMap<D::Key, WatchedEvent<D::NotificationValue>>,
    filter: Option<D::Key>,
) -> Vec<NotificationType<D>> {
    use collect::CollectEvents;

    // First, collect the events by kind.
    let mut removes = CollectEvents::None;
    let mut upserts = CollectEvents::None;
    // Collecting clear events degenerates into a simple bool.
    let mut clear = false;
    for (k, e) in events {
        // We could have separate functions for one key vs the whole table and be a little bit more
        // efficient. I don't think it would be a huge difference though.
        if let Some(f) = &filter
            && f != k
        {
            continue;
        }

        match e {
            WatchedEvent::Clear => clear = true,
            WatchedEvent::Remove => removes.push(k.clone(), ()),
            WatchedEvent::Upsert(v) => upserts.push(k.clone(), v),
            WatchedEvent::KeyOnlyUpsert => upserts.force_many(k.clone()),
        }
    }

    // Then convert the collected events into a public notification.
    let mut result = Vec::with_capacity(3);
    if clear {
        result.push(D::make_notification(Event::TableClear));
    }
    match removes {
        CollectEvents::None => {}
        CollectEvents::One(k, _) => result.push(D::make_notification(Event::KeyRemove(k.clone()))),
        CollectEvents::Many(ks) => result.push(D::make_notification(Event::TableRemove(ks))),
    }
    match upserts {
        CollectEvents::None => {}
        CollectEvents::One(k, v) => {
            result.push(D::make_notification(Event::KeyUpsert(k.clone(), v.clone())))
        }
        CollectEvents::Many(ks) => result.push(D::make_notification(Event::TableUpsert(ks))),
    }
    result
}

// Helper type for getting the generated, public notification enum for the store from a table description `D`.
type NotificationType<D> =
    <<D as TableDesc>::Storage as crate::schema::GeneratedStorage>::Notification;

mod collect {
    /// Helper type for collecting a table's events into the shapes used by the public notification API.
    ///
    /// Some events are reported as single events, including the key and (maybe) value. Some events are
    /// grouped together for reporting (either because many events occurred or always) and only the keys
    /// are reported. `CollectEvents` gathers events into whichever of those two formats applies.
    pub enum CollectEvents<K, V> {
        None,
        One(K, V),
        Many(Vec<K>),
    }

    impl<K, V> CollectEvents<K, V> {
        /// Add an event.
        pub fn push(&mut self, k: K, v: V) {
            match self {
                CollectEvents::None => *self = CollectEvents::One(k, v),
                CollectEvents::One(..) => {
                    let prev = std::mem::replace(self, CollectEvents::None);
                    let CollectEvents::One(k0, _) = prev else {
                        unreachable!();
                    };
                    *self = CollectEvents::Many(vec![k0, k]);
                }
                CollectEvents::Many(ks) => ks.push(k),
            }
        }

        /// Add an event and (if not already) convert the collection into the `Many` variant. Used
        /// where an event should always be reported as a list of keys rather than key and value.
        pub fn force_many(&mut self, k: K) {
            match self {
                CollectEvents::None => *self = CollectEvents::Many(vec![k]),
                CollectEvents::One(..) => {
                    let prev = std::mem::replace(self, CollectEvents::None);
                    let CollectEvents::One(k0, _) = prev else {
                        unreachable!();
                    };
                    *self = CollectEvents::Many(vec![k0, k]);
                }
                CollectEvents::Many(ks) => ks.push(k),
            }
        }
    }

    #[cfg(test)]
    mod tests {
        use super::*;

        fn variant<K, V>(c: &CollectEvents<K, V>) -> &'static str {
            match c {
                CollectEvents::None => "none",
                CollectEvents::One(..) => "one",
                CollectEvents::Many(..) => "many",
            }
        }

        fn many<K: Clone, V>(c: &CollectEvents<K, V>) -> Vec<K> {
            match c {
                CollectEvents::Many(ks) => ks.clone(),
                _ => panic!("expected Many"),
            }
        }

        #[test]
        fn push_transitions_none_one_many() {
            let mut c: CollectEvents<u32, &str> = CollectEvents::None;
            assert_eq!(variant(&c), "none");

            c.push(1, "a");
            assert_eq!(variant(&c), "one");

            // Second push promotes One -> Many, keeping both keys in insertion order.
            c.push(2, "b");
            assert_eq!(variant(&c), "many");
            assert_eq!(many(&c), vec![1, 2]);

            // Further pushes append to the existing Many.
            c.push(3, "c");
            assert_eq!(many(&c), vec![1, 2, 3]);
        }

        #[test]
        fn force_many_always_produces_many() {
            // None -> Many directly.
            let mut c: CollectEvents<u32, &str> = CollectEvents::None;
            c.force_many(1);
            assert_eq!(variant(&c), "many");
            assert_eq!(many(&c), vec![1]);

            // One -> Many, preserving the earlier key.
            let mut c: CollectEvents<u32, &str> = CollectEvents::None;
            c.push(1, "a");
            c.force_many(2);
            assert_eq!(many(&c), vec![1, 2]);

            // Many -> Many appends.
            c.force_many(3);
            assert_eq!(many(&c), vec![1, 2, 3]);
        }
    }
}

#[cfg(test)]
mod tests {
    use std::{
        collections::HashMap,
        num::NonZeroUsize,
        sync::{Arc, Mutex},
    };

    use super::*;
    use crate::{Error, storage::SinValue, store};

    store!(
        kvs: {
            Count(u64; OWNER),
            Shared(String as Arc; OWNER),
        }
        tables: {
            Items(u32 => String; OWNER; notify(Clone)),
            Plain(u32 => String; OWNER),
        }
    );

    const OWNER: &str = "owner";

    // --- A mock `Notifier` that records everything it is handed. ------------------------------

    /// Recorded `notify` calls. The `Vec` is one map (subscription -> notifications) per committed
    /// transaction.
    type RecordedCalls = Arc<Mutex<Vec<HashMap<Subscription, Vec<Notification>>>>>;

    /// Records the notifications passed to `notify`, one entry per `notify` call (i.e., per
    /// committed transaction).
    #[derive(Clone)]
    struct RecordingNotifier {
        calls: RecordedCalls,
    }

    impl std::fmt::Debug for RecordingNotifier {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
            f.debug_struct("RecordingNotifier").finish()
        }
    }

    impl RecordingNotifier {
        /// Returns the notifier as a trait object (for `KvStore::new`) plus a handle sharing the
        /// same buffer for assertions.
        fn new() -> (
            Arc<dyn Notifier<Notification = Notification>>,
            RecordingNotifier,
        ) {
            let rec = RecordingNotifier {
                calls: Arc::new(Mutex::new(Vec::new())),
            };
            (Arc::new(rec.clone()), rec)
        }

        /// Number of `notify` calls seen so far.
        fn total_calls(&self) -> usize {
            self.calls.lock().unwrap().len()
        }

        fn reset(&self) {
            self.calls.lock().unwrap().clear();
        }

        /// All notifications delivered to `sub`, across every recorded call, in order.
        fn notifications_for(&self, sub: Subscription) -> Vec<Notification> {
            self.calls
                .lock()
                .unwrap()
                .iter()
                .flat_map(|m| m.get(&sub).cloned().unwrap_or_default())
                .collect()
        }
    }

    impl Notifier for RecordingNotifier {
        type Notification = Notification;

        fn notify(&self, notifications: Notifications<Notification>) {
            self.calls.lock().unwrap().push(notifications.into());
        }
    }

    // Helpers for asserting on the generated (non-`PartialEq`, non-`Debug`) notifications.

    /// A comparable projection of an `Items` notification. Key lists are sorted because the
    /// underlying events come from a `HashMap` and so have no deterministic order.
    #[derive(Debug, PartialEq)]
    enum ItemsKind {
        KeyUpsert(u32, String),
        KeyRemove(u32),
        TableUpsert(Vec<u32>),
        TableRemove(Vec<u32>),
        TableClear,
    }

    impl From<&Notification> for ItemsKind {
        fn from(n: &Notification) -> ItemsKind {
            let Notification::Items(e) = n else {
                panic!();
            };
            match e {
                Event::KeyUpsert(k, v) => ItemsKind::KeyUpsert(*k, v.clone()),
                Event::KeyRemove(k) => ItemsKind::KeyRemove(*k),
                Event::TableUpsert(ks) => {
                    let mut ks = ks.clone();
                    ks.sort();
                    ItemsKind::TableUpsert(ks)
                }
                Event::TableRemove(ks) => {
                    let mut ks = ks.clone();
                    ks.sort();
                    ItemsKind::TableRemove(ks)
                }
                Event::TableClear => ItemsKind::TableClear,
                _ => unreachable!(),
            }
        }
    }

    /// A comparable projection of a `Count` singleton notification.
    #[derive(Debug, PartialEq)]
    enum CountKind {
        Upsert(u64),
        Remove,
    }

    impl From<&Notification> for CountKind {
        fn from(n: &Notification) -> CountKind {
            let Notification::Count(e) = n else {
                panic!();
            };
            match e {
                SingletonEvent::Upsert(v) => CountKind::Upsert(*v),
                SingletonEvent::Remove => CountKind::Remove,
                _ => unreachable!(),
            }
        }
    }

    fn upsert(v: &str) -> WatchedEvent<String> {
        WatchedEvent::Upsert(v.to_owned())
    }

    fn events(pairs: &[(u32, WatchedEvent<String>)]) -> HashMap<u32, WatchedEvent<String>> {
        pairs.iter().cloned().collect()
    }

    fn make_subscription(id: usize) -> Subscription {
        Subscription(
            NonZeroUsize::new(id).unwrap(),
            Subscriber(NonZeroUsize::new(id).unwrap()),
        )
    }

    #[test]
    fn process_events_empty() {
        let result = process_events::<Items>(&HashMap::new(), None);
        assert!(result.is_empty());
    }

    #[test]
    fn process_events_single_upsert_is_key_upsert() {
        let result = process_events::<Items>(&events(&[(1, upsert("a"))]), None);
        assert_eq!(result.len(), 1);
        assert_eq!(
            ItemsKind::from(&result[0]),
            ItemsKind::KeyUpsert(1, "a".to_owned())
        );
    }

    #[test]
    fn process_events_many_upserts_are_table_upsert() {
        let result = process_events::<Items>(&events(&[(1, upsert("a")), (2, upsert("b"))]), None);
        assert_eq!(result.len(), 1);
        assert_eq!(
            ItemsKind::from(&result[0]),
            ItemsKind::TableUpsert(vec![1, 2])
        );
    }

    #[test]
    fn process_events_single_remove_is_key_remove() {
        let result = process_events::<Items>(&events(&[(1, WatchedEvent::Remove)]), None);
        assert_eq!(result.len(), 1);
        assert_eq!(ItemsKind::from(&result[0]), ItemsKind::KeyRemove(1));
    }

    #[test]
    fn process_events_many_removes_are_table_remove() {
        let result = process_events::<Items>(
            &events(&[(1, WatchedEvent::Remove), (2, WatchedEvent::Remove)]),
            None,
        );
        assert_eq!(result.len(), 1);
        assert_eq!(
            ItemsKind::from(&result[0]),
            ItemsKind::TableRemove(vec![1, 2])
        );
    }

    #[test]
    fn process_events_single_init_is_table_upsert() {
        // `Init` (empty -> non-empty) is always reported as a table-level upsert, even for one key.
        let result = process_events::<Items>(&events(&[(1, WatchedEvent::KeyOnlyUpsert)]), None);
        assert_eq!(result.len(), 1);
        assert_eq!(ItemsKind::from(&result[0]), ItemsKind::TableUpsert(vec![1]));
    }

    #[test]
    fn process_events_init_and_upsert_coalesce_to_table_upsert() {
        let result = process_events::<Items>(
            &events(&[(1, WatchedEvent::KeyOnlyUpsert), (2, upsert("b"))]),
            None,
        );
        assert_eq!(result.len(), 1);
        assert_eq!(
            ItemsKind::from(&result[0]),
            ItemsKind::TableUpsert(vec![1, 2])
        );
    }

    #[test]
    fn process_events_clear_is_table_clear() {
        let result = process_events::<Items>(&events(&[(1, WatchedEvent::Clear)]), None);
        assert_eq!(result.len(), 1);
        assert_eq!(ItemsKind::from(&result[0]), ItemsKind::TableClear);
    }

    #[test]
    fn process_events_filter_selects_only_matching_key() {
        let evs = events(&[(1, upsert("a")), (2, upsert("b"))]);

        let matched = process_events::<Items>(&evs, Some(1));
        assert_eq!(matched.len(), 1);
        assert_eq!(
            ItemsKind::from(&matched[0]),
            ItemsKind::KeyUpsert(1, "a".to_owned())
        );

        let missing = process_events::<Items>(&evs, Some(3));
        assert!(missing.is_empty());
    }

    #[test]
    fn notifications_default_is_empty() {
        let n = Notifications::<Notification>::default();
        let map: HashMap<Subscription, Vec<Notification>> = n.into();
        assert!(map.is_empty());
    }

    #[test]
    fn notifications_append_accumulates_per_subscription() {
        let mut n = Notifications::<Notification>::default();
        let a = make_subscription(1);
        let b = make_subscription(2);

        n.append_notifications(a, &[Notification::Items(Event::TableClear)]);
        n.append_notifications(a, &[Notification::Items(Event::KeyRemove(7))]);
        n.append_notifications(b, &[Notification::Items(Event::TableClear)]);

        let map: HashMap<Subscription, Vec<Notification>> = n.into();
        assert_eq!(map[&a].len(), 2);
        assert_eq!(ItemsKind::from(&map[&a][0]), ItemsKind::TableClear);
        assert_eq!(ItemsKind::from(&map[&a][1]), ItemsKind::KeyRemove(7));
        assert_eq!(map[&b].len(), 1);
    }

    fn new_subscriptions() -> Subscriptions<Notification> {
        Subscriptions::new(NoOpNotifier::<Notification>::new())
    }

    #[test]
    fn register_subscriber_yields_distinct_ids() {
        let subs = new_subscriptions();
        let a = subs.register_subscriber(OWNER);
        let b = subs.register_subscriber(OWNER);
        assert_ne!(a, b);
    }

    #[test]
    fn register_subscription_rejects_unknown_subscriber() {
        let subs = new_subscriptions();
        let bogus = Subscriber(NonZeroUsize::new(1).unwrap());
        assert_eq!(
            subs.register_subscription(bogus),
            Err(Error::UnknownSubscriber)
        );
    }

    #[test]
    fn register_subscription_carries_its_subscriber() {
        let subs = new_subscriptions();
        let subscriber = subs.register_subscriber(OWNER);
        let subscription = subs.register_subscription(subscriber).unwrap();
        assert_eq!(subscription.1, subscriber);
    }

    #[test]
    fn global_subscription_receives_table_events() {
        let subs = new_subscriptions();
        let subscriber = subs.register_subscriber(OWNER);
        let sub = subs.create_global_subscription(subscriber).unwrap();

        let mut notifs = Notifications::default();
        subs.collect_events::<Items>(&mut notifs, events(&[(1, upsert("a"))]));

        let map: HashMap<Subscription, Vec<Notification>> = notifs.into();
        assert_eq!(
            ItemsKind::from(&map[&sub][0]),
            ItemsKind::KeyUpsert(1, "a".to_owned())
        );
    }

    #[test]
    fn whole_table_subscription_receives_all_keys() {
        let subs = new_subscriptions();
        let subscriber = subs.register_subscriber(OWNER);
        let sub = subs
            .create_table_subscription_all::<Items>(subscriber)
            .unwrap();

        let mut notifs = Notifications::default();
        subs.collect_events::<Items>(&mut notifs, events(&[(1, upsert("a")), (2, upsert("b"))]));

        let map: HashMap<Subscription, Vec<Notification>> = notifs.into();
        assert_eq!(
            ItemsKind::from(&map[&sub][0]),
            ItemsKind::TableUpsert(vec![1, 2])
        );
    }

    #[test]
    fn single_key_subscription_filters_other_keys() {
        let subs = new_subscriptions();
        let subscriber = subs.register_subscriber(OWNER);
        let sub = subs
            .create_table_subscription::<Items>(1, subscriber)
            .unwrap();

        let mut notifs = Notifications::default();
        subs.collect_events::<Items>(&mut notifs, events(&[(1, upsert("a")), (2, upsert("b"))]));

        let map: HashMap<Subscription, Vec<Notification>> = notifs.into();
        assert_eq!(map[&sub].len(), 1);
        assert_eq!(
            ItemsKind::from(&map[&sub][0]),
            ItemsKind::KeyUpsert(1, "a".to_owned())
        );
    }

    #[test]
    fn removed_table_subscription_receives_nothing() {
        let subs = new_subscriptions();
        let subscriber = subs.register_subscriber(OWNER);
        let sub = subs
            .create_table_subscription_all::<Items>(subscriber)
            .unwrap();
        subs.remove_table_subscription::<Items>(sub);

        let mut notifs = Notifications::default();
        subs.collect_events::<Items>(&mut notifs, events(&[(1, upsert("a"))]));

        let map: HashMap<Subscription, Vec<Notification>> = notifs.into();
        assert!(!map.contains_key(&sub));
    }

    #[test]
    fn singleton_subscription_receives_upsert_and_remove() {
        let subs = new_subscriptions();
        let subscriber = subs.register_subscriber(OWNER);
        let sub = subs
            .create_singleton_subscription::<Count>(subscriber)
            .unwrap();

        let mut notifs = Notifications::default();
        subs.collect_singleton_events::<Count>(&mut notifs, &SinValue::U64(5));
        let map: HashMap<Subscription, Vec<Notification>> = notifs.into();
        assert_eq!(CountKind::from(&map[&sub][0]), CountKind::Upsert(5));

        let mut notifs = Notifications::default();
        subs.collect_singleton_events::<Count>(&mut notifs, &SinValue::None);
        let map: HashMap<Subscription, Vec<Notification>> = notifs.into();
        assert_eq!(CountKind::from(&map[&sub][0]), CountKind::Remove);
    }

    #[test]
    fn global_subscription_receives_singleton_events() {
        let subs = new_subscriptions();
        let subscriber = subs.register_subscriber(OWNER);
        let sub = subs.create_global_subscription(subscriber).unwrap();

        let mut notifs = Notifications::default();
        subs.collect_singleton_events::<Count>(&mut notifs, &SinValue::U64(5));

        let map: HashMap<Subscription, Vec<Notification>> = notifs.into();
        assert_eq!(CountKind::from(&map[&sub][0]), CountKind::Upsert(5));
    }

    #[test]
    fn removed_global_subscription_receives_nothing() {
        let subs = new_subscriptions();
        let subscriber = subs.register_subscriber(OWNER);
        let sub = subs.create_global_subscription(subscriber).unwrap();
        subs.remove_global_subscription(sub);

        let mut notifs = Notifications::default();
        subs.collect_events::<Items>(&mut notifs, events(&[(1, upsert("a"))]));
        subs.collect_singleton_events::<Count>(&mut notifs, &SinValue::U64(5));

        let map: HashMap<Subscription, Vec<Notification>> = notifs.into();
        assert!(!map.contains_key(&sub));
    }

    #[test]
    fn removed_singleton_subscription_receives_nothing() {
        let subs = new_subscriptions();
        let subscriber = subs.register_subscriber(OWNER);
        let sub = subs
            .create_singleton_subscription::<Count>(subscriber)
            .unwrap();
        subs.remove_singleton_subscription::<Count>(sub);

        let mut notifs = Notifications::default();
        subs.collect_singleton_events::<Count>(&mut notifs, &SinValue::U64(5));
        let map: HashMap<Subscription, Vec<Notification>> = notifs.into();
        assert!(!map.contains_key(&sub));
    }

    #[test]
    fn key_subscription_with_no_matching_events_has_no_entry() {
        let subs = new_subscriptions();
        let subscriber = subs.register_subscriber(OWNER);
        let sub = subs
            .create_table_subscription::<Items>(1, subscriber)
            .unwrap();

        let mut notifs = Notifications::default();
        subs.collect_events::<Items>(&mut notifs, events(&[(2, upsert("b"))]));

        // Nothing matched the filter, so the subscription must not appear at all (rather than
        // appearing with an empty list of notifications).
        let map: HashMap<Subscription, Vec<Notification>> = notifs.into();
        assert!(!map.contains_key(&sub));
    }

    #[test]
    fn has_subscribers_false_when_no_subscriptions() {
        let subs = new_subscriptions();
        assert!(!subs.has_subscribers::<Items>());
        assert!(!subs.has_singleton_subscribers::<Count>());
    }

    #[test]
    fn has_subscribers_true_for_whole_table_subscription() {
        let subs = new_subscriptions();
        let subscriber = subs.register_subscriber(OWNER);
        subs.create_table_subscription_all::<Items>(subscriber)
            .unwrap();

        assert!(subs.has_subscribers::<Items>());
        // Subscribing to one table says nothing about any other table.
        assert!(!subs.has_subscribers::<Plain>());
        assert!(!subs.has_singleton_subscribers::<Count>());
    }

    #[test]
    fn has_subscribers_true_for_key_subscription() {
        let subs = new_subscriptions();
        let subscriber = subs.register_subscriber(OWNER);
        subs.create_table_subscription::<Items>(1, subscriber)
            .unwrap();

        assert!(subs.has_subscribers::<Items>());
        assert!(!subs.has_subscribers::<Plain>());
    }

    #[test]
    fn has_subscribers_true_for_global_subscription() {
        let subs = new_subscriptions();
        let subscriber = subs.register_subscriber(OWNER);
        subs.create_global_subscription(subscriber).unwrap();

        // A global subscription watches everything, including tables and singletons which have no
        // subscription state of their own.
        assert!(subs.has_subscribers::<Items>());
        assert!(subs.has_subscribers::<Plain>());
        assert!(subs.has_singleton_subscribers::<Count>());
        assert!(subs.has_singleton_subscribers::<Shared>());
    }

    #[test]
    fn has_subscribers_false_after_removing_whole_table_subscription() {
        let subs = new_subscriptions();
        let subscriber = subs.register_subscriber(OWNER);
        let sub = subs
            .create_table_subscription_all::<Items>(subscriber)
            .unwrap();
        subs.remove_table_subscription::<Items>(sub);

        assert!(!subs.has_subscribers::<Items>());
    }

    #[test]
    fn has_subscribers_over_approximates_after_removing_key_subscription() {
        let subs = new_subscriptions();
        let subscriber = subs.register_subscriber(OWNER);
        let sub = subs
            .create_table_subscription::<Items>(1, subscriber)
            .unwrap();
        subs.remove_table_subscription::<Items>(sub);

        // Removing a key subscription leaves an empty entry for that key behind, so the answer is
        // a false positive. That is permitted (only false negatives would be a bug) and collecting
        // events for the table still produces no notifications.
        assert!(subs.has_subscribers::<Items>());

        let mut notifs = Notifications::default();
        subs.collect_events::<Items>(&mut notifs, events(&[(1, upsert("a"))]));
        let map: HashMap<Subscription, Vec<Notification>> = notifs.into();
        assert!(map.is_empty());
    }

    #[test]
    fn has_subscribers_false_after_removing_global_subscription() {
        let subs = new_subscriptions();
        let subscriber = subs.register_subscriber(OWNER);
        let sub = subs.create_global_subscription(subscriber).unwrap();
        subs.remove_global_subscription(sub);

        assert!(!subs.has_subscribers::<Items>());
        assert!(!subs.has_singleton_subscribers::<Count>());
    }

    #[test]
    fn has_singleton_subscribers_is_per_singleton() {
        let subs = new_subscriptions();
        let subscriber = subs.register_subscriber(OWNER);
        subs.create_singleton_subscription::<Count>(subscriber)
            .unwrap();

        assert!(subs.has_singleton_subscribers::<Count>());
        assert!(!subs.has_singleton_subscribers::<Shared>());
        assert!(!subs.has_subscribers::<Items>());
    }

    #[test]
    fn has_singleton_subscribers_false_after_removal() {
        let subs = new_subscriptions();
        let subscriber = subs.register_subscriber(OWNER);
        let sub = subs
            .create_singleton_subscription::<Count>(subscriber)
            .unwrap();
        subs.remove_singleton_subscription::<Count>(sub);

        // Unlike the table case, singleton removal is precise.
        assert!(!subs.has_singleton_subscribers::<Count>());
    }

    #[test]
    fn has_subscribers_true_while_any_subscription_remains() {
        let subs = new_subscriptions();
        let subscriber = subs.register_subscriber(OWNER);
        let gone = subs
            .create_table_subscription_all::<Items>(subscriber)
            .unwrap();
        subs.create_table_subscription_all::<Items>(subscriber)
            .unwrap();
        subs.remove_table_subscription::<Items>(gone);

        assert!(subs.has_subscribers::<Items>());
    }

    #[test]
    fn on_commit_forwards_to_notifier() {
        let (notifier, rec) = RecordingNotifier::new();
        let subs = Subscriptions::new(notifier);
        subs.on_commit(Notifications::default());
        assert_eq!(rec.total_calls(), 1);
    }

    #[test]
    fn e2e_single_key_subscription() {
        let (notifier, rec) = RecordingNotifier::new();
        let store = KvStore::with_notifier(notifier);
        let subscriber = store.register_subscriber(OWNER);

        // Pre-populate before subscribing so the table is non-empty (a first insert into an empty
        // table is reported as a table-level upsert, not a per-key one).
        store.table::<Items>(OWNER).insert(99, "x".to_owned());
        let sub = store
            .table::<Items>(OWNER)
            .subscribe_key(subscriber, 1)
            .unwrap();
        rec.reset();

        store.table::<Items>(OWNER).insert(1, "one".to_owned());
        store.table::<Items>(OWNER).insert(2, "two".to_owned());
        store.table::<Items>(OWNER).remove(&1);

        let got = rec.notifications_for(sub);
        // The insert of key 2 is filtered out; only key 1's upsert and removal remain.
        assert_eq!(
            got.iter().map(ItemsKind::from).collect::<Vec<_>>(),
            vec![
                ItemsKind::KeyUpsert(1, "one".to_owned()),
                ItemsKind::KeyRemove(1)
            ]
        );
    }

    #[test]
    fn e2e_whole_table_subscription() {
        let (notifier, rec) = RecordingNotifier::new();
        let store = KvStore::with_notifier(notifier);
        let subscriber = store.register_subscriber(OWNER);
        let sub = store.table::<Items>(OWNER).subscribe(subscriber).unwrap();
        rec.reset();

        let mut txn = store.begin_transaction(OWNER);
        {
            let mut t = txn.table::<Items>();
            t.insert(1, "a".to_owned());
            t.insert(2, "b".to_owned());
        }
        txn.commit().unwrap();
        store.table::<Items>(OWNER).clear();

        let got = rec.notifications_for(sub);
        assert_eq!(
            got.iter().map(ItemsKind::from).collect::<Vec<_>>(),
            vec![ItemsKind::TableUpsert(vec![1, 2]), ItemsKind::TableClear]
        );
    }

    #[test]
    fn e2e_global_subscription_sees_all_tables() {
        let (notifier, rec) = RecordingNotifier::new();
        let store = KvStore::with_notifier(notifier);
        let subscriber = store.register_subscriber(OWNER);
        let sub = store.subscribe_global(subscriber).unwrap();
        rec.reset();

        store.table::<Items>(OWNER).insert(1, "a".to_owned());
        store.table::<Plain>(OWNER).insert(2, "b".to_owned());

        let got = rec.notifications_for(sub);
        assert_eq!(got.len(), 2);
        assert_eq!(ItemsKind::from(&got[0]), ItemsKind::TableUpsert(vec![1]));
        assert!(matches!(
            &got[1],
            Notification::Plain(Event::TableUpsert(_))
        ));
    }

    #[test]
    fn e2e_global_subscription_sees_singletons() {
        let (notifier, rec) = RecordingNotifier::new();
        let store = KvStore::with_notifier(notifier);
        let subscriber = store.register_subscriber(OWNER);
        let sub = store.subscribe_global(subscriber).unwrap();
        rec.reset();

        store.insert::<Count>(OWNER, 7);
        store.remove::<Count>(OWNER);

        assert_eq!(
            rec.notifications_for(sub)
                .iter()
                .map(CountKind::from)
                .collect::<Vec<_>>(),
            vec![CountKind::Upsert(7), CountKind::Remove]
        );
    }

    #[test]
    fn e2e_first_insert_into_empty_table_is_table_upsert() {
        let (notifier, rec) = RecordingNotifier::new();
        let store = KvStore::with_notifier(notifier);
        let subscriber = store.register_subscriber(OWNER);
        let sub = store.table::<Items>(OWNER).subscribe(subscriber).unwrap();
        rec.reset();

        // The very first insert takes the table from empty to non-empty and so is reported as a
        // table-level upsert...
        store.table::<Items>(OWNER).insert(1, "a".to_owned());
        // ...but a later insert into the now non-empty table is a per-key upsert.
        store.table::<Items>(OWNER).insert(2, "b".to_owned());

        assert_eq!(
            rec.notifications_for(sub)
                .iter()
                .map(ItemsKind::from)
                .collect::<Vec<_>>(),
            vec![
                ItemsKind::TableUpsert(vec![1]),
                ItemsKind::KeyUpsert(2, "b".to_owned()),
            ]
        );
    }

    #[test]
    fn e2e_singleton_subscription() {
        let (notifier, rec) = RecordingNotifier::new();
        let store = KvStore::with_notifier(notifier);
        let subscriber = store.register_subscriber(OWNER);
        let sub = store.subscribe::<Count>(subscriber).unwrap();
        rec.reset();

        store.insert::<Count>(OWNER, 42);
        store.remove::<Count>(OWNER);

        let got = rec.notifications_for(sub);
        assert_eq!(
            got.iter().map(CountKind::from).collect::<Vec<_>>(),
            vec![CountKind::Upsert(42), CountKind::Remove]
        );
    }

    #[test]
    fn e2e_arc_singleton_subscription() {
        let (notifier, rec) = RecordingNotifier::new();
        let store = KvStore::with_notifier(notifier);
        let subscriber = store.register_subscriber(OWNER);
        let sub = store.subscribe::<Shared>(subscriber).unwrap();
        rec.reset();

        store.insert::<Shared>(OWNER, Arc::new("hello".to_owned()));
        store.remove::<Shared>(OWNER);

        let got = rec.notifications_for(sub);
        assert_eq!(got.len(), 2);
        match &got[0] {
            Notification::Shared(SingletonEvent::Upsert(v)) => assert_eq!(v.as_str(), "hello"),
            _ => panic!("expected a Shared upsert"),
        }
        assert!(matches!(
            &got[1],
            Notification::Shared(SingletonEvent::Remove)
        ));
    }

    #[test]
    fn e2e_notifications_grouped_by_subscription() {
        let (notifier, rec) = RecordingNotifier::new();
        let store = KvStore::with_notifier(notifier);
        let subscriber_a = store.register_subscriber(OWNER);
        let subscriber_b = store.register_subscriber(OWNER);

        store.table::<Items>(OWNER).insert(99, "x".to_owned());
        let key_sub = store
            .table::<Items>(OWNER)
            .subscribe_key(subscriber_a, 1)
            .unwrap();
        let table_sub = store.table::<Items>(OWNER).subscribe(subscriber_b).unwrap();
        rec.reset();

        store.table::<Items>(OWNER).insert(1, "one".to_owned());

        assert_eq!(
            rec.notifications_for(key_sub)
                .iter()
                .map(ItemsKind::from)
                .collect::<Vec<_>>(),
            vec![ItemsKind::KeyUpsert(1, "one".to_owned())]
        );
        assert_eq!(
            rec.notifications_for(table_sub)
                .iter()
                .map(ItemsKind::from)
                .collect::<Vec<_>>(),
            vec![ItemsKind::KeyUpsert(1, "one".to_owned())]
        );
    }

    #[test]
    fn e2e_unsubscribe_stops_notifications() {
        let (notifier, rec) = RecordingNotifier::new();
        let store = KvStore::with_notifier(notifier);
        let subscriber = store.register_subscriber(OWNER);
        let sub = store.table::<Items>(OWNER).subscribe(subscriber).unwrap();

        store.table::<Items>(OWNER).unsubscribe(sub);
        rec.reset();

        store.table::<Items>(OWNER).insert(1, "a".to_owned());
        assert!(rec.notifications_for(sub).is_empty());
    }

    #[test]
    fn e2e_unsubscribe_global_stops_notifications() {
        let (notifier, rec) = RecordingNotifier::new();
        let store = KvStore::with_notifier(notifier);
        let subscriber = store.register_subscriber(OWNER);
        let gone = store.subscribe_global(subscriber).unwrap();
        let kept = store.subscribe_global(subscriber).unwrap();

        store.unsubscribe_global(gone);
        rec.reset();

        store.table::<Items>(OWNER).insert(1, "a".to_owned());
        store.insert::<Count>(OWNER, 7);

        assert!(rec.notifications_for(gone).is_empty());
        // Removing one global subscription must leave the others in place.
        let kept = rec.notifications_for(kept);
        assert_eq!(kept.len(), 2);
        assert_eq!(ItemsKind::from(&kept[0]), ItemsKind::TableUpsert(vec![1]));
        assert_eq!(CountKind::from(&kept[1]), CountKind::Upsert(7));
    }

    /// Seed `Items` with `keys` (mapping each key `k` to the value `"v{k}"`) in a committed
    /// transaction, so that later mutations are reported per-key rather than as a table-level
    /// `Init`.
    fn seed_items(store: &KvStore, keys: &[u32]) {
        let mut txn = store.begin_transaction(OWNER);
        {
            let mut t = txn.table::<Items>();
            for k in keys {
                t.insert(*k, format!("v{k}"));
            }
        }
        txn.commit().unwrap();
    }

    #[test]
    fn e2e_iter_mut_notifies_visited_keys() {
        let (notifier, rec) = RecordingNotifier::new();
        let store = KvStore::with_notifier(notifier);
        let subscriber = store.register_subscriber(OWNER);
        let sub = store.table::<Items>(OWNER).subscribe(subscriber).unwrap();
        seed_items(&store, &[1, 2]);
        rec.reset();

        let mut txn = store.begin_transaction(OWNER);
        {
            let mut table = txn.table::<Items>();
            for (_, v) in table.iter_mut() {
                v.push('!');
            }
        }
        txn.commit().unwrap();

        let got = rec.notifications_for(sub);
        assert_eq!(got.len(), 1);
        assert_eq!(ItemsKind::from(&got[0]), ItemsKind::TableUpsert(vec![1, 2]));
    }

    #[test]
    fn e2e_iter_mut_notifies_key_subscription() {
        let (notifier, rec) = RecordingNotifier::new();
        let store = KvStore::with_notifier(notifier);
        let subscriber = store.register_subscriber(OWNER);
        let sub = store
            .table::<Items>(OWNER)
            .subscribe_key(subscriber, 1)
            .unwrap();
        seed_items(&store, &[1, 2]);
        rec.reset();

        let mut txn = store.begin_transaction(OWNER);
        {
            let mut table = txn.table::<Items>();
            for (_, v) in table.iter_mut() {
                v.push('!');
            }
        }
        txn.commit().unwrap();

        // Only key 1 is notified, and the notification carries the post-mutation value.
        let got = rec.notifications_for(sub);
        assert_eq!(
            got.iter().map(ItemsKind::from).collect::<Vec<_>>(),
            vec![ItemsKind::KeyUpsert(1, "v1!".to_owned())]
        );
    }

    #[test]
    fn e2e_partial_iter_mut_notifies_only_visited_keys() {
        let (notifier, rec) = RecordingNotifier::new();
        let store = KvStore::with_notifier(notifier);
        let subscriber = store.register_subscriber(OWNER);
        let sub = store.table::<Items>(OWNER).subscribe(subscriber).unwrap();
        seed_items(&store, &[1, 2]);
        rec.reset();

        let mut txn = store.begin_transaction(OWNER);
        {
            let mut table = txn.table::<Items>();
            table.iter_mut().next().unwrap().1.push('!');
        }
        txn.commit().unwrap();

        // Only the single row the iterator handed out is notified. Which row that is depends on
        // `HashMap` order, so accept either.
        let got = rec.notifications_for(sub);
        assert_eq!(got.len(), 1);
        let got = ItemsKind::from(&got[0]);
        assert!(
            got == ItemsKind::KeyUpsert(1, "v1!".to_owned())
                || got == ItemsKind::KeyUpsert(2, "v2!".to_owned()),
            "unexpected notification: {got:?}"
        );
    }

    #[test]
    fn e2e_iter_mut_with_remove_in_same_txn() {
        let (notifier, rec) = RecordingNotifier::new();
        let store = KvStore::with_notifier(notifier);
        let subscriber = store.register_subscriber(OWNER);
        let sub = store.table::<Items>(OWNER).subscribe(subscriber).unwrap();
        seed_items(&store, &[1, 2, 3]);
        rec.reset();

        let mut txn = store.begin_transaction(OWNER);
        {
            let mut table = txn.table::<Items>();
            table.remove(&2);
            // `iter_mut` skips the removed key, so key 2 is only reported as a removal.
            for (_, v) in table.iter_mut() {
                v.push('!');
            }
        }
        txn.commit().unwrap();

        assert_eq!(
            rec.notifications_for(sub)
                .iter()
                .map(ItemsKind::from)
                .collect::<Vec<_>>(),
            vec![ItemsKind::KeyRemove(2), ItemsKind::TableUpsert(vec![1, 3])]
        );
    }

    #[test]
    fn e2e_iter_mut_on_empty_table_notifies_nothing() {
        let (notifier, rec) = RecordingNotifier::new();
        let store = KvStore::with_notifier(notifier);
        let subscriber = store.register_subscriber(OWNER);
        let sub = store.table::<Items>(OWNER).subscribe(subscriber).unwrap();
        rec.reset();

        let mut txn = store.begin_transaction(OWNER);
        {
            let mut table = txn.table::<Items>();
            assert_eq!(table.iter_mut().count(), 0);
        }
        txn.commit().unwrap();

        assert!(rec.notifications_for(sub).is_empty());
    }

    #[test]
    fn e2e_rolled_back_transaction_notifies_nothing() {
        let (notifier, rec) = RecordingNotifier::new();
        let store = KvStore::with_notifier(notifier);
        let subscriber = store.register_subscriber(OWNER);
        let _sub = store.table::<Items>(OWNER).subscribe(subscriber).unwrap();
        rec.reset();

        {
            let mut txn = store.begin_transaction(OWNER);
            txn.table::<Items>().insert(1, "a".to_owned());
            // Dropped without `commit`, so the transaction rolls back and never notifies.
        }

        assert_eq!(rec.total_calls(), 0);
    }

    #[test]
    fn e2e_mutations_coalesced_within_one_transaction() {
        let (notifier, rec) = RecordingNotifier::new();
        let store = KvStore::with_notifier(notifier);
        let subscriber = store.register_subscriber(OWNER);
        let sub = store.table::<Items>(OWNER).subscribe(subscriber).unwrap();
        rec.reset();

        let mut txn = store.begin_transaction(OWNER);
        {
            let mut t = txn.table::<Items>();
            t.insert(1, "a".to_owned());
            t.insert(2, "b".to_owned());
            t.insert(3, "c".to_owned());
        }
        txn.commit().unwrap();

        // A single commit produces a single notification carrying all three keys.
        assert_eq!(rec.total_calls(), 1);
        let got = rec.notifications_for(sub);
        assert_eq!(got.len(), 1);
        assert_eq!(
            ItemsKind::from(&got[0]),
            ItemsKind::TableUpsert(vec![1, 2, 3])
        );
    }

    #[test]
    fn e2e_insert_then_remove_in_one_txn_notifies_nothing() {
        let (notifier, rec) = RecordingNotifier::new();
        let store = KvStore::with_notifier(notifier);
        let subscriber = store.register_subscriber(OWNER);
        let sub = store.table::<Items>(OWNER).subscribe(subscriber).unwrap();
        // Seed an unrelated key so the table is non-empty and the transaction below is not an
        // empty -> non-empty transition.
        seed_items(&store, &[9]);
        rec.reset();

        let mut txn = store.begin_transaction(OWNER);
        {
            let mut t = txn.table::<Items>();
            t.insert(1, "a".to_owned());
            t.remove(&1);
        }
        txn.commit().unwrap();

        // Key 1 was never visible outside the transaction, so its removal is not notifiable.
        assert!(rec.notifications_for(sub).is_empty());
    }

    #[test]
    fn e2e_insert_then_remove_in_one_txn_still_reports_other_keys() {
        let (notifier, rec) = RecordingNotifier::new();
        let store = KvStore::with_notifier(notifier);
        let subscriber = store.register_subscriber(OWNER);
        let sub = store.table::<Items>(OWNER).subscribe(subscriber).unwrap();
        seed_items(&store, &[9]);
        rec.reset();

        let mut txn = store.begin_transaction(OWNER);
        {
            let mut t = txn.table::<Items>();
            t.insert(1, "a".to_owned());
            t.remove(&1);
            // A key which did exist before the transaction is still reported as removed.
            t.remove(&9);
        }
        txn.commit().unwrap();

        assert_eq!(
            rec.notifications_for(sub)
                .iter()
                .map(ItemsKind::from)
                .collect::<Vec<_>>(),
            vec![ItemsKind::KeyRemove(9)]
        );
    }

    #[test]
    fn e2e_insert_then_clear_in_one_txn_notifies_nothing() {
        let (notifier, rec) = RecordingNotifier::new();
        let store = KvStore::with_notifier(notifier);
        let subscriber = store.register_subscriber(OWNER);
        let sub = store.table::<Items>(OWNER).subscribe(subscriber).unwrap();
        rec.reset();

        let mut txn = store.begin_transaction(OWNER);
        {
            let mut t = txn.table::<Items>();
            t.insert(1, "a".to_owned());
            t.clear();
        }
        txn.commit().unwrap();

        // The table was empty before the transaction and is empty after it, so there is nothing
        // for a subscriber to hear about.
        assert!(rec.notifications_for(sub).is_empty());
    }

    #[test]
    fn e2e_clear_of_populated_table_still_notifies() {
        let (notifier, rec) = RecordingNotifier::new();
        let store = KvStore::with_notifier(notifier);
        let subscriber = store.register_subscriber(OWNER);
        let sub = store.table::<Items>(OWNER).subscribe(subscriber).unwrap();
        seed_items(&store, &[1]);
        rec.reset();

        let mut txn = store.begin_transaction(OWNER);
        {
            let mut t = txn.table::<Items>();
            t.insert(2, "b".to_owned());
            t.clear();
        }
        txn.commit().unwrap();

        // Key 1 pre-dated the transaction, so clearing it is notifiable even though key 2 (created
        // and cleared within the transaction) is not.
        assert_eq!(
            rec.notifications_for(sub)
                .iter()
                .map(ItemsKind::from)
                .collect::<Vec<_>>(),
            vec![ItemsKind::TableClear]
        );
    }

    #[test]
    fn e2e_subscribe_and_notify_singleton_sends_current_value() {
        let (notifier, rec) = RecordingNotifier::new();
        let store = KvStore::with_notifier(notifier);
        let subscriber = store.register_subscriber(OWNER);
        store.insert::<Count>(OWNER, 6);
        store.insert::<Count>(OWNER, 7);
        rec.reset();

        // Subscribing delivers the current value immediately, before any further mutation.
        let sub = store.subscribe_and_notify::<Count>(subscriber).unwrap();

        assert_eq!(
            rec.notifications_for(sub)
                .iter()
                .map(CountKind::from)
                .collect::<Vec<_>>(),
            vec![CountKind::Upsert(7)]
        );
    }

    #[test]
    fn e2e_subscribe_and_notify_singleton_without_value_sends_nothing() {
        let (notifier, rec) = RecordingNotifier::new();
        let store = KvStore::with_notifier(notifier);
        let subscriber = store.register_subscriber(OWNER);
        rec.reset();

        let sub = store.subscribe_and_notify::<Count>(subscriber).unwrap();

        // There is no current value, so nothing is sent and no `notify` call is made at all.
        assert!(rec.notifications_for(sub).is_empty());
        assert_eq!(rec.total_calls(), 0);
    }

    #[test]
    fn e2e_subscribe_and_notify_singleton_then_receives_updates() {
        let (notifier, rec) = RecordingNotifier::new();
        let store = KvStore::with_notifier(notifier);
        let subscriber = store.register_subscriber(OWNER);
        store.insert::<Count>(OWNER, 7);
        rec.reset();

        let sub = store.subscribe_and_notify::<Count>(subscriber).unwrap();
        store.insert::<Count>(OWNER, 8);
        store.remove::<Count>(OWNER);

        // The initial value is followed by the ordinary stream of subsequent updates.
        assert_eq!(
            rec.notifications_for(sub)
                .iter()
                .map(CountKind::from)
                .collect::<Vec<_>>(),
            vec![
                CountKind::Upsert(7),
                CountKind::Upsert(8),
                CountKind::Remove
            ]
        );
    }

    #[test]
    fn e2e_subscribe_and_notify_arc_singleton_sends_current_value() {
        let (notifier, rec) = RecordingNotifier::new();
        let store = KvStore::with_notifier(notifier);
        let subscriber = store.register_subscriber(OWNER);
        store.insert::<Shared>(OWNER, Arc::new("hello".to_owned()));
        rec.reset();

        let sub = store.subscribe_and_notify::<Shared>(subscriber).unwrap();

        let got = rec.notifications_for(sub);
        assert_eq!(got.len(), 1);
        match &got[0] {
            Notification::Shared(SingletonEvent::Upsert(v)) => assert_eq!(v.as_str(), "hello"),
            _ => panic!("expected a Shared upsert"),
        }
    }

    #[test]
    fn e2e_subscribe_key_and_notify_sends_current_value() {
        let (notifier, rec) = RecordingNotifier::new();
        let store = KvStore::with_notifier(notifier);
        let subscriber = store.register_subscriber(OWNER);
        store.table::<Items>(OWNER).insert(1, "one".to_owned());
        rec.reset();

        let sub = store
            .table::<Items>(OWNER)
            .subscribe_key_and_notify(subscriber, 1)
            .unwrap();

        // The current value is always delivered as a per-key upsert, even though key 1 is the only
        // key in the table (a live first-insert into an empty table would be a table-level upsert).
        assert_eq!(
            rec.notifications_for(sub)
                .iter()
                .map(ItemsKind::from)
                .collect::<Vec<_>>(),
            vec![ItemsKind::KeyUpsert(1, "one".to_owned())]
        );
    }

    #[test]
    fn e2e_subscribe_key_and_notify_missing_key_sends_nothing() {
        let (notifier, rec) = RecordingNotifier::new();
        let store = KvStore::with_notifier(notifier);
        let subscriber = store.register_subscriber(OWNER);
        // The table is non-empty, but does not contain the key being subscribed to.
        store.table::<Items>(OWNER).insert(2, "two".to_owned());
        rec.reset();

        let sub = store
            .table::<Items>(OWNER)
            .subscribe_key_and_notify(subscriber, 1)
            .unwrap();

        assert!(rec.notifications_for(sub).is_empty());
        assert_eq!(rec.total_calls(), 0);
    }

    fn items_snapshot(store: &KvStore) -> Vec<(u32, String)> {
        let txn = store.begin_ro_transaction(OWNER);
        let mut items: Vec<_> = txn
            .table::<Items>()
            .iter()
            .map(|(k, v)| (*k, v.clone()))
            .collect();
        items.sort();
        items
    }

    #[test]
    fn e2e_no_subscribers_commits_inserts_and_removes() {
        let (notifier, _rec) = RecordingNotifier::new();
        let store = KvStore::with_notifier(notifier);

        store.table::<Items>(OWNER).insert(1, "a".to_owned());
        store.table::<Items>(OWNER).insert(2, "b".to_owned());
        store.table::<Items>(OWNER).insert(2, "b2".to_owned());
        store.table::<Items>(OWNER).remove(&1);

        assert_eq!(items_snapshot(&store), vec![(2, "b2".to_owned())]);
        assert_eq!(store.table::<Items>(OWNER).get(&1), None);
    }

    #[test]
    fn e2e_no_subscribers_commits_mixed_mutations_in_one_txn() {
        let (notifier, _rec) = RecordingNotifier::new();
        let store = KvStore::with_notifier(notifier);
        seed_items(&store, &[1, 2, 3]);

        let mut txn = store.begin_transaction(OWNER);
        {
            let mut t = txn.table::<Items>();
            t.remove(&2);
            t.insert(4, "v4".to_owned());
            t.with_mut(&1, |v| v.push('!'));
        }
        txn.commit().unwrap();

        assert_eq!(
            items_snapshot(&store),
            vec![
                (1, "v1!".to_owned()),
                (3, "v3".to_owned()),
                (4, "v4".to_owned())
            ]
        );
    }

    #[test]
    fn e2e_no_subscribers_commits_clear() {
        let (notifier, _rec) = RecordingNotifier::new();
        let store = KvStore::with_notifier(notifier);
        seed_items(&store, &[1, 2]);

        // Clear and re-insert within one transaction, so the commit takes the "clear everything,
        // then restore these keys" path with notification collection turned off.
        let mut txn = store.begin_transaction(OWNER);
        {
            let mut t = txn.table::<Items>();
            t.clear();
            t.insert(3, "c".to_owned());
        }
        txn.commit().unwrap();

        assert_eq!(items_snapshot(&store), vec![(3, "c".to_owned())]);

        store.table::<Items>(OWNER).clear();
        assert!(items_snapshot(&store).is_empty());
        assert!(store.table::<Items>(OWNER).is_empty());
    }

    #[test]
    fn e2e_unwatched_table_commits_while_watched_table_notifies() {
        let (notifier, rec) = RecordingNotifier::new();
        let store = KvStore::with_notifier(notifier);
        let subscriber = store.register_subscriber(OWNER);
        // Only `Items` is watched; `Plain` is committed without collecting notifications.
        let sub = store.table::<Items>(OWNER).subscribe(subscriber).unwrap();
        rec.reset();

        let mut txn = store.begin_transaction(OWNER);
        {
            txn.table::<Items>().insert(1, "a".to_owned());
            txn.table::<Plain>().insert(2, "b".to_owned());
        }
        txn.commit().unwrap();

        assert_eq!(store.table::<Plain>(OWNER).get(&2), Some("b".to_owned()));
        assert_eq!(
            rec.notifications_for(sub)
                .iter()
                .map(ItemsKind::from)
                .collect::<Vec<_>>(),
            vec![ItemsKind::TableUpsert(vec![1])]
        );
    }

    #[test]
    fn e2e_subscribing_after_unwatched_inserts_sees_per_key_upserts() {
        let (notifier, rec) = RecordingNotifier::new();
        let store = KvStore::with_notifier(notifier);
        let subscriber = store.register_subscriber(OWNER);

        // Committed with no subscribers, so no events are collected for it...
        store.table::<Items>(OWNER).insert(1, "a".to_owned());

        let sub = store.table::<Items>(OWNER).subscribe(subscriber).unwrap();
        rec.reset();

        // ...but the table is still known to be non-empty, so the next insert is a per-key upsert
        // rather than an empty -> non-empty table upsert.
        store.table::<Items>(OWNER).insert(2, "b".to_owned());
        // Likewise, removing the key inserted while unwatched is still a notifiable removal.
        store.table::<Items>(OWNER).remove(&1);

        assert_eq!(
            rec.notifications_for(sub)
                .iter()
                .map(ItemsKind::from)
                .collect::<Vec<_>>(),
            vec![
                ItemsKind::KeyUpsert(2, "b".to_owned()),
                ItemsKind::KeyRemove(1)
            ]
        );
    }

    #[test]
    fn e2e_subscribing_after_unwatched_clear_sees_table_upsert() {
        let (notifier, rec) = RecordingNotifier::new();
        let store = KvStore::with_notifier(notifier);
        let subscriber = store.register_subscriber(OWNER);

        seed_items(&store, &[1, 2]);
        store.table::<Items>(OWNER).clear();

        let sub = store.table::<Items>(OWNER).subscribe(subscriber).unwrap();
        rec.reset();

        // The unwatched clear really did empty the table, so this insert is an empty -> non-empty
        // transition.
        store.table::<Items>(OWNER).insert(3, "c".to_owned());

        assert_eq!(
            rec.notifications_for(sub)
                .iter()
                .map(ItemsKind::from)
                .collect::<Vec<_>>(),
            vec![ItemsKind::TableUpsert(vec![3])]
        );
    }

    #[test]
    fn e2e_no_singleton_subscribers_commits_value() {
        let (notifier, _rec) = RecordingNotifier::new();
        let store = KvStore::with_notifier(notifier);

        store.insert::<Count>(OWNER, 7);
        assert_eq!(store.get::<Count>(OWNER), Some(7));

        store.remove::<Count>(OWNER);
        assert_eq!(store.get::<Count>(OWNER), None);
    }

    #[test]
    fn e2e_unwatched_singleton_commits_while_watched_one_notifies() {
        let (notifier, rec) = RecordingNotifier::new();
        let store = KvStore::with_notifier(notifier);
        let subscriber = store.register_subscriber(OWNER);
        let sub = store.subscribe::<Count>(subscriber).unwrap();
        rec.reset();

        let mut txn = store.begin_transaction(OWNER);
        txn.insert::<Count>(1);
        txn.insert::<Shared>(Arc::new("hello".to_owned()));
        txn.commit().unwrap();

        assert_eq!(
            store.get_arc::<Shared>(OWNER).as_deref(),
            Some(&"hello".to_owned())
        );
        // Only `Count` is watched, so only its event is delivered.
        assert_eq!(
            rec.notifications_for(sub)
                .iter()
                .map(CountKind::from)
                .collect::<Vec<_>>(),
            vec![CountKind::Upsert(1)]
        );
    }

    #[test]
    fn e2e_subscribing_after_unwatched_singleton_writes_sees_later_updates() {
        let (notifier, rec) = RecordingNotifier::new();
        let store = KvStore::with_notifier(notifier);
        let subscriber = store.register_subscriber(OWNER);

        store.insert::<Count>(OWNER, 7);
        let sub = store.subscribe::<Count>(subscriber).unwrap();
        rec.reset();

        store.insert::<Count>(OWNER, 8);

        assert_eq!(
            rec.notifications_for(sub)
                .iter()
                .map(CountKind::from)
                .collect::<Vec<_>>(),
            vec![CountKind::Upsert(8)]
        );
    }
}
