[package]
name = "ts_transport"
version.workspace = true
description = "packet transport traits and types for tailscale"
categories = ["network-programming", "asynchronous"]
keywords = ["tailscale", "packet", "network", "transport"]

repository.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
# Our crates.
ts_packet.workspace = true
ts_hexdump.workspace = true

smallbox = { version = "0.8", default-features = false }
dyn-hash = "1.0"
dyn-eq = "0.1"

[lints]
workspace = true
