[package]
name = "ts_netmon"
version.workspace = true
description = "tailscale network interface monitor"
categories = ["network-programming"]
keywords = ["tailscale", "network", "monitor", "netmon"]

repository.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
cfg-if.workspace = true
flume.workspace = true
futures-util.workspace = true
ipnet.workspace = true
pin-project-lite = "0.2"
smallvec.workspace = true
tokio.workspace = true
tokio-stream = "0.1"
tracing.workspace = true
itertools.workspace = true
bytes.workspace = true
heapless.workspace = true
static_assertions.workspace = true
regex = "1.13"
ts_future_util.workspace = true

[dev-dependencies]
ts_cli_util.workspace = true
clap.workspace = true
tracing-test = { version = "0.2", features = ["no-env-filter"] }

[target.'cfg(windows)'.dependencies]
windows = { version = "0.62", features = [
    "Win32_NetworkManagement_IpHelper",
    "Win32_NetworkManagement_Ndis",
    "Win32_Networking_WinSock",
] }

[target.'cfg(target_os = "linux")'.dependencies]
rtnetlink = "0.21"

[target.'cfg(target_os = "macos")'.dependencies]
nom = "8.0"
zerocopy = { version = "0.8", features = ["derive"] }
nix = "0.31"
libc = "0.2"
bitflags = "2.13"
socket2 = "0.6"
tokio = { workspace = true, features = ["net"] }

[lints]
workspace = true
