//! KvStore non-transactional API.

use std::{borrow::Borrow, hash::Hash, marker::PhantomData, sync::Arc};

use crate::{
    Error, KvStore, Owner, Result,
    operations::{Ops, SingletonOps, TabularOps},
    schema::{self, GeneratedStorage, Notifiable},
    storage::Storage,
    transactions::SchemaTransaction,
};

/// Access singleton data in the store.
///
/// `S` describes the data; instances are generated by the schema macros.
pub struct Singleton<
    TableStorage: schema::GeneratedStorage + 'static,
    S: schema::SingletonDesc<Storage = TableStorage>,
> {
    store: Arc<KvStore<TableStorage>>,
    desc: PhantomData<S>,
}

impl<
    TableStorage: schema::GeneratedStorage + 'static,
    S: schema::SingletonDesc<Storage = TableStorage>,
> Singleton<TableStorage, S>
{
    #[doc(hidden)]
    pub fn new(store: Arc<KvStore<TableStorage>>) -> Self {
        Singleton {
            store,
            desc: PhantomData,
        }
    }

    /// Subscribe to a singleton key-value pair.
    pub fn subscribe(
        &self,
        subscriber: impl Into<crate::Subscriber>,
    ) -> Result<crate::Subscription> {
        self.store
            .get_read_lock()
            .subscriptions
            .create_singleton_subscription::<S>(subscriber.into())
    }

    /// Subscribe to a singleton key-value pair and send the current value (if any) to the subscriber.
    pub fn subscribe_and_notify(
        &self,
        subscriber: impl Into<crate::Subscriber>,
    ) -> Result<crate::Subscription> {
        let storage = self.store.get_read_lock();
        let subs = &storage.subscriptions;
        let id = subs.create_singleton_subscription::<S>(subscriber.into())?;

        crate::pub_sub::send_current_singleton::<S>(subs, &storage, id);

        Ok(id)
    }

    /// Unsubscribe to a singleton key-value pair.
    pub fn unsubscribe(&self, subscription: crate::Subscription) {
        self.store
            .get_read_lock()
            .subscriptions
            .remove_singleton_subscription::<S>(subscription)
    }

    /// Get a single value from the store by cloning the value.
    ///
    /// Returns `None` if there is no value for the specified key.
    pub fn get(&self, owner: Owner) -> Option<S::Value>
    where
        S::Value: Clone,
    {
        <&Self as SingletonOps<_>>::get::<S>(self, owner)
    }

    /// Get immutable access to a value in the store by reference.
    ///
    /// Returns `None` (and does not call `f`) if there is no value for the specified key.
    pub fn with<T>(&self, owner: Owner, f: impl FnOnce(&S::Value) -> T) -> Option<T> {
        <&Self as SingletonOps<_>>::with::<S, T>(self, f, owner)
    }

    /// Get mutable access to a value in the store by reference.
    ///
    /// Returns `None` (and does not call `f`) if there is no value for the specified key.
    pub fn with_mut<T>(&self, owner: Owner, f: impl FnOnce(&mut S::Value) -> T) -> Option<T>
    where
        S::Value: Clone + PartialEq,
    {
        in_txn_infallible(&self.store, owner, |txn| S::make_txn_view(txn).with_mut(f))
    }

    /// Insert a single value into the store.
    pub fn insert(&self, owner: Owner, value: S::Value) {
        in_txn_infallible(&self.store, owner, |txn| {
            S::make_txn_view(txn).insert(value)
        })
    }

    /// Remove a single value from the store.
    pub fn remove(&self, owner: Owner) {
        in_txn_infallible(&self.store, owner, |txn| S::make_txn_view(txn).remove())
    }
}

impl<
    'store,
    TableStorage: schema::GeneratedStorage + 'static,
    S: schema::SingletonDesc<Storage = TableStorage>,
> Ops<TableStorage> for &'store Singleton<TableStorage, S>
{
    type ReadLock = std::sync::RwLockReadGuard<'store, Storage<TableStorage>>;

    fn read_lock(self) -> Self::ReadLock {
        self.store.get_read_lock()
    }
}

impl<
    TableStorage: schema::GeneratedStorage + 'static,
    S: schema::SingletonDesc<Storage = TableStorage>,
> SingletonOps<TableStorage> for &Singleton<TableStorage, S>
{
}

/// Apply `f` to a new transaction which contains only that operation, then commit it.
///
/// Returns the error from committing, if there is one.
fn in_txn<TableStorage: GeneratedStorage, T>(
    store: &KvStore<TableStorage>,
    owner: Owner,
    f: impl FnOnce(&mut TableStorage::Transaction<'_>) -> T,
) -> Result<T> {
    let mut txn = store.begin_transaction(owner);
    let result = f(&mut txn);
    txn.commit()?;
    Ok(result)
}

/// Like `in_txn`, but for operations which can't cause the commit to fail.
///
/// Committing a transaction only fails if an index is made non-unique or an operation panics (in
/// which case the panic unwinds out of this function before committing).
fn in_txn_infallible<TableStorage: GeneratedStorage, T>(
    store: &KvStore<TableStorage>,
    owner: Owner,
    f: impl FnOnce(&mut TableStorage::Transaction<'_>) -> T,
) -> T {
    in_txn(store, owner, f).expect("committing a single-operation transaction failed")
}

/// Access tabular data in the store.
///
/// `D` describes the table and instances are generated by the schema macros.
pub struct Table<
    TableStorage: schema::GeneratedStorage + 'static,
    D: Notifiable<Storage = TableStorage>,
> {
    store: Arc<KvStore<TableStorage>>,
    desc: PhantomData<D>,
}

impl<TableStorage: schema::GeneratedStorage + 'static, D: Notifiable<Storage = TableStorage>>
    Table<TableStorage, D>
{
    #[doc(hidden)]
    pub fn new(store: Arc<KvStore<TableStorage>>) -> Self {
        Table {
            store,
            desc: PhantomData,
        }
    }

    /// The number of key/value pairs in the table.
    pub fn len(&self) -> usize {
        <&Self as TabularOps<_>>::len(self)
    }

    /// True if the table is empty.
    pub fn is_empty(&self) -> bool {
        <&Self as TabularOps<_>>::is_empty(self)
    }

    /// Clear a table by removing all its KVs.
    pub fn clear(&self, owner: Owner) {
        in_txn_infallible(&self.store, owner, |txn| D::make_txn_view(txn).clear())
    }

    /// Get a row of the table from the store by cloning the value.
    ///
    /// Returns `None` if there is no value for the specified key.
    pub fn get<Q>(&self, owner: Owner, key: &Q) -> Option<D::Value>
    where
        D::Value: Clone,
        D::Key: Borrow<Q>,
        Q: ?Sized + Hash + Eq,
    {
        <&Self as TabularOps<_>>::get(self, key, owner)
    }

    /// Get immutable access to a row of the table in the store by reference.
    ///
    /// Returns `None` (and does not call `f`) if there is no value for the specified key.
    pub fn with<Q, T>(&self, owner: Owner, key: &Q, f: impl FnOnce(&D::Value) -> T) -> Option<T>
    where
        D::Key: Borrow<Q>,
        Q: ?Sized + Hash + Eq,
    {
        <&Self as TabularOps<_>>::with(self, key, f, owner)
    }

    /// Insert `value` into the table.
    ///
    /// Panics if a value is already indexed with the same index key.
    pub fn insert(&self, owner: Owner, key: D::Key, value: D::Value) {
        self.try_insert(owner, key, value).unwrap();
    }

    /// Insert a `value` into the table.
    ///
    /// Returns an error if `insert` would panic.
    pub fn try_insert(&self, owner: Owner, key: D::Key, value: D::Value) -> Result<()> {
        in_txn(&self.store, owner, |txn| {
            D::make_txn_view(txn).insert(key, value)
        })
    }

    /// Get mutable access to a row of the table.
    ///
    /// Returns `Error::NotPresent` (and does not call `f`) if there is no value for the specified key.
    pub fn with_mut<Q, T>(
        &self,
        owner: Owner,
        key: &Q,
        f: impl FnOnce(&mut D::Value) -> T,
    ) -> Result<T>
    where
        D::Key: Borrow<Q>,
        Q: ?Sized + Hash + Eq + ToOwned<Owned = D::Key>,
        D::Value: Clone + PartialEq,
    {
        in_txn(&self.store, owner, |txn| {
            D::make_txn_view(txn).with_mut(key, f)
        })?
        .ok_or(Error::NotPresent)
    }

    /// Remove a row from the table.
    pub fn remove<Q>(&self, owner: Owner, key: &Q)
    where
        D::Key: Borrow<Q>,
        Q: ?Sized + Hash + Eq + ToOwned<Owned = D::Key>,
    {
        in_txn_infallible(&self.store, owner, |txn| D::make_txn_view(txn).remove(key))
    }

    /// Iterate over all key/value pairs in the table.
    ///
    /// Access is scoped by a closure (rather than returning an iterator) because the store is
    /// locked while iterating, and so references into the store must not outlive the iterator.
    /// Use a (read-only) transaction to get an iterator.
    pub fn with_iter<F, T>(&self, _owner: Owner, f: F) -> T
    where
        F: for<'a> FnOnce(&mut dyn Iterator<Item = (&'a D::Key, &'a D::Value)>) -> T,
    {
        <&Self as TabularOps<_>>::with_iter(self, f)
    }

    /// Iterate over all keys in the table.
    pub fn with_keys<F, T>(&self, _owner: Owner, f: F) -> T
    where
        F: for<'a> FnOnce(&mut dyn Iterator<Item = &'a D::Key>) -> T,
    {
        <&Self as TabularOps<_>>::with_keys(self, f)
    }

    /// Iterate over all values in the table.
    pub fn with_values<F, T>(&self, _owner: Owner, f: F) -> T
    where
        F: for<'a> FnOnce(&mut dyn Iterator<Item = &'a D::Value>) -> T,
    {
        <&Self as TabularOps<_>>::with_values(self, f)
    }

    /// Iterate over all key/value pairs in the table, with mutable access to the
    /// values.
    ///
    /// Access is scoped by a closure because the table's indexes are updated from the mutated
    /// values once `f` returns.
    ///
    /// Returns `Error::NonUniqueIndexKey` if `f` makes a unique index key non-unique, in which
    /// case none of the mutations are applied.
    pub fn with_iter_mut<F, T>(&self, owner: Owner, f: F) -> Result<T>
    where
        F: for<'a> FnOnce(&mut dyn Iterator<Item = (&'a D::Key, &'a mut D::Value)>) -> T,
        D::Value: Clone + PartialEq,
    {
        in_txn(&self.store, owner, |txn| {
            D::make_txn_view(txn).with_iter_mut(f)
        })
    }

    /// Iterate over all values in the table, with mutable access.
    pub fn with_values_mut<F, T>(&self, owner: Owner, f: F) -> Result<T>
    where
        F: for<'a> FnOnce(&mut dyn Iterator<Item = &'a mut D::Value>) -> T,
        D::Value: Clone + PartialEq,
    {
        in_txn(&self.store, owner, |txn| {
            D::make_txn_view(txn).with_values_mut(f)
        })
    }

    /// Subscribe to the whole table.
    pub fn subscribe(&self, subscriber: impl Into<crate::Subscriber>) -> Result<crate::Subscription>
    where
        D::Key: Send,
    {
        self.store
            .get_read_lock()
            .subscriptions
            .create_table_subscription_all::<D>(subscriber.into())
    }

    /// Unsubscribe from the table (whole table or single key).
    pub fn unsubscribe(&self, subscription: crate::Subscription) {
        self.store
            .get_read_lock()
            .subscriptions
            .remove_table_subscription::<D>(subscription);
    }

    /// Subscribe to a specific key in the table.
    pub fn subscribe_key(
        &self,
        subscriber: impl Into<crate::Subscriber>,
        key: D::Key,
    ) -> Result<crate::Subscription>
    where
        D::Key: Send,
    {
        self.store
            .get_read_lock()
            .subscriptions
            .create_table_subscription::<D>(key, subscriber.into())
    }

    /// Subscribe to a specific key in the table and send the current value (if any) to the subscriber.
    pub fn subscribe_key_and_notify(
        &self,
        subscriber: impl Into<crate::Subscriber>,
        key: D::Key,
    ) -> Result<crate::Subscription>
    where
        D::Key: Send,
    {
        let storage = self.store.get_read_lock();
        let subs = &storage.subscriptions;
        let id = subs.create_table_subscription::<D>(key.clone(), subscriber.into())?;

        crate::pub_sub::send_current::<D>(subs, &storage, key, id);

        Ok(id)
    }
}

impl<
    TableStorage: schema::GeneratedStorage + 'static,
    D: schema::Indexable + Notifiable<Storage = TableStorage>,
> Table<TableStorage, D>
{
    /// Access the table via its indexes.
    ///
    /// Returns a macro-generated struct with a field for each index declared for the table; each
    /// field is an [`Index`](crate::Index) which gives access to the table using that index's key.
    ///
    /// # Example:
    ///
    /// ```rust,ignore
    /// let value = store.Foo.indexes().bar.get(OWNER, key).unwrap();
    /// ```
    ///
    /// Where `Foo` is a table and `bar` is an index over `Foo` using the `bar` field as foreign key.
    pub fn indexes(&self) -> D::Indexes {
        Arc::clone(&self.store).into()
    }
}

impl<
    'store,
    TableStorage: schema::GeneratedStorage + 'static,
    D: Notifiable<Storage = TableStorage>,
> Ops<TableStorage> for &'store Table<TableStorage, D>
{
    type ReadLock = std::sync::RwLockReadGuard<'store, Storage<TableStorage>>;

    fn read_lock(self) -> Self::ReadLock {
        self.store.get_read_lock()
    }
}

impl<TableStorage: schema::GeneratedStorage + 'static, D: Notifiable<Storage = TableStorage>>
    TabularOps<TableStorage> for &Table<TableStorage, D>
{
    type TableDesc = D;
}

/// A singleton in the store, accessed with a fixed owner.
///
/// The owner-carrying version of [`Singleton`]. The operations are the same, but the owner is
/// supplied once rather than on each call.
pub struct SingletonWithOwner<
    TableStorage: schema::GeneratedStorage + 'static,
    S: schema::SingletonDesc<Storage = TableStorage>,
> {
    inner: Singleton<TableStorage, S>,
    owner: Owner,
}

impl<
    TableStorage: schema::GeneratedStorage + 'static,
    S: schema::SingletonDesc<Storage = TableStorage>,
> SingletonWithOwner<TableStorage, S>
{
    #[doc(hidden)]
    pub fn new(store: Arc<KvStore<TableStorage>>, owner: Owner) -> Self {
        SingletonWithOwner {
            inner: Singleton::new(store),
            owner,
        }
    }

    /// Subscribe to a singleton key-value pair.
    pub fn subscribe(
        &self,
        subscriber: impl Into<crate::Subscriber>,
    ) -> Result<crate::Subscription> {
        self.inner.subscribe(subscriber)
    }

    /// Subscribe to a singleton key-value pair and send the current value (if any) to the subscriber.
    pub fn subscribe_and_notify(
        &self,
        subscriber: impl Into<crate::Subscriber>,
    ) -> Result<crate::Subscription> {
        self.inner.subscribe_and_notify(subscriber)
    }

    /// Unsubscribe to a singleton key-value pair.
    pub fn unsubscribe(&self, subscription: crate::Subscription) {
        self.inner.unsubscribe(subscription)
    }

    /// Get a single value from the store by cloning the value.
    ///
    /// Returns `None` if there is no value for the specified key.
    pub fn get(&self) -> Option<S::Value>
    where
        S::Value: Clone,
    {
        self.inner.get(self.owner)
    }

    /// Get immutable access to a value in the store by reference.
    ///
    /// Returns `None` (and does not call `f`) if there is no value for the specified key.
    pub fn with<T>(&self, f: impl FnOnce(&S::Value) -> T) -> Option<T> {
        self.inner.with(self.owner, f)
    }

    /// Get mutable access to a value in the store by reference.
    ///
    /// Returns `None` (and does not call `f`) if there is no value for the specified key.
    pub fn with_mut<T>(&self, f: impl FnOnce(&mut S::Value) -> T) -> Option<T>
    where
        S::Value: Clone + PartialEq,
    {
        self.inner.with_mut(self.owner, f)
    }

    /// Insert a single value into the store.
    pub fn insert(&self, value: S::Value) {
        self.inner.insert(self.owner, value)
    }

    /// Remove a single value from the store.
    pub fn remove(&self) {
        self.inner.remove(self.owner)
    }
}

/// A table of key/value pairs in the store, accessed with a fixed owner.
///
/// The owner-carrying versiom of [`Table`]. The operations are the same, but the owner is
/// supplied once rather than on each call.
pub struct TableWithOwner<
    TableStorage: schema::GeneratedStorage + 'static,
    D: Notifiable<Storage = TableStorage>,
> {
    inner: Table<TableStorage, D>,
    owner: Owner,
}

impl<TableStorage: schema::GeneratedStorage + 'static, D: Notifiable<Storage = TableStorage>>
    TableWithOwner<TableStorage, D>
{
    #[doc(hidden)]
    pub fn new(store: Arc<KvStore<TableStorage>>, owner: Owner) -> Self {
        TableWithOwner {
            inner: Table::new(store),
            owner,
        }
    }

    /// The number of key/value pairs in the table.
    pub fn len(&self) -> usize {
        self.inner.len()
    }

    /// True if the table is empty.
    pub fn is_empty(&self) -> bool {
        self.inner.is_empty()
    }

    /// Clear a table by removing all its KVs.
    pub fn clear(&self) {
        self.inner.clear(self.owner)
    }

    /// Get a row of the table from the store by cloning the value.
    ///
    /// Returns `None` if there is no value for the specified key.
    pub fn get<Q>(&self, key: &Q) -> Option<D::Value>
    where
        D::Value: Clone,
        D::Key: Borrow<Q>,
        Q: ?Sized + Hash + Eq,
    {
        self.inner.get(self.owner, key)
    }

    /// Get immutable access to a row of the table in the store by reference.
    ///
    /// Returns `None` (and does not call `f`) if there is no value for the specified key.
    pub fn with<Q, T>(&self, key: &Q, f: impl FnOnce(&D::Value) -> T) -> Option<T>
    where
        D::Key: Borrow<Q>,
        Q: ?Sized + Hash + Eq,
    {
        self.inner.with(self.owner, key, f)
    }

    /// Insert a `value` into the table.
    ///
    /// Panics if a value is already indexed with the same index key.
    pub fn insert(&self, key: D::Key, value: D::Value) {
        self.inner.insert(self.owner, key, value)
    }

    /// Insert a `value` into the table.
    ///
    /// Returns an error if `insert` would panic.
    pub fn try_insert(&self, key: D::Key, value: D::Value) -> Result<()> {
        self.inner.try_insert(self.owner, key, value)
    }

    /// Get mutable access to a row of the table in the store in the store.
    ///
    /// Returns `Error::NotPresent` (and does not call `f`) if there is no value for the specified key.
    pub fn with_mut<Q, T>(&self, key: &Q, f: impl FnOnce(&mut D::Value) -> T) -> Result<T>
    where
        D::Key: Borrow<Q>,
        Q: ?Sized + Hash + Eq + ToOwned<Owned = D::Key>,
        D::Value: Clone + PartialEq,
    {
        self.inner.with_mut(self.owner, key, f)
    }

    /// Remove a row from the table.
    pub fn remove<Q>(&self, key: &Q)
    where
        D::Key: Borrow<Q>,
        Q: ?Sized + Hash + Eq + ToOwned<Owned = D::Key>,
    {
        self.inner.remove(self.owner, key)
    }

    /// Iterate over all key/value pairs in the table.
    ///
    /// Access is scoped by a closure (rather than returning an iterator) because the store is
    /// locked while iterating, and so references into the store must not outlive the iterator.
    /// Use a (read-only) transaction to get an iterator.
    pub fn with_iter<F, T>(&self, f: F) -> T
    where
        F: for<'a> FnOnce(&mut dyn Iterator<Item = (&'a D::Key, &'a D::Value)>) -> T,
    {
        self.inner.with_iter(self.owner, f)
    }

    /// Iterate over all keys in the table.
    pub fn with_keys<F, T>(&self, f: F) -> T
    where
        F: for<'a> FnOnce(&mut dyn Iterator<Item = &'a D::Key>) -> T,
    {
        self.inner.with_keys(self.owner, f)
    }

    /// Iterate over all values in the table.
    pub fn with_values<F, T>(&self, f: F) -> T
    where
        F: for<'a> FnOnce(&mut dyn Iterator<Item = &'a D::Value>) -> T,
    {
        self.inner.with_values(self.owner, f)
    }

    /// Iterate over all key/value pairs in the table, with mutable access to the
    /// values.
    ///
    /// Access is scoped by a closure because the table's indexes are updated from the mutated
    /// values once `f` returns.
    ///
    /// Returns `Error::NonUniqueIndexKey` if `f` makes a unique index key non-unique, in which
    /// case none of the mutations are applied.
    pub fn with_iter_mut<F, T>(&self, f: F) -> Result<T>
    where
        F: for<'a> FnOnce(&mut dyn Iterator<Item = (&'a D::Key, &'a mut D::Value)>) -> T,
        D::Value: Clone + PartialEq,
    {
        self.inner.with_iter_mut(self.owner, f)
    }

    /// Iterate over all values in the table, with mutable access.
    pub fn with_values_mut<F, T>(&self, f: F) -> Result<T>
    where
        F: for<'a> FnOnce(&mut dyn Iterator<Item = &'a mut D::Value>) -> T,
        D::Value: Clone + PartialEq,
    {
        self.inner.with_values_mut(self.owner, f)
    }

    /// Subscribe to the whole table.
    pub fn subscribe(&self, subscriber: impl Into<crate::Subscriber>) -> Result<crate::Subscription>
    where
        D::Key: Send,
    {
        self.inner.subscribe(subscriber)
    }

    /// Unsubscribe from the table (whole table or single key).
    pub fn unsubscribe(&self, subscription: crate::Subscription) {
        self.inner.unsubscribe(subscription)
    }

    /// Subscribe to a specific key in the table.
    pub fn subscribe_key(
        &self,
        subscriber: impl Into<crate::Subscriber>,
        key: D::Key,
    ) -> Result<crate::Subscription>
    where
        D::Key: Send,
    {
        self.inner.subscribe_key(subscriber, key)
    }

    /// Subscribe to a specific key in the table and send the current value (if any) to the subscriber.
    pub fn subscribe_key_and_notify(
        &self,
        subscriber: impl Into<crate::Subscriber>,
        key: D::Key,
    ) -> Result<crate::Subscription>
    where
        D::Key: Send,
    {
        self.inner.subscribe_key_and_notify(subscriber, key)
    }
}

impl<
    TableStorage: schema::GeneratedStorage + 'static,
    D: schema::Indexable + Notifiable<Storage = TableStorage>,
> TableWithOwner<TableStorage, D>
{
    /// Access the table via its indexes.
    ///
    /// Returns a macro-generated struct with a field for each index declared for the table; each
    /// field is an [`IndexWithOwner`](crate::IndexWithOwner) which gives access to the table using
    /// that index's key.
    ///
    /// # Example:
    ///
    /// ```rust,ignore
    /// let value = store.with_owner(OWNER).Foo.indexes().bar.get(key).unwrap();
    /// ```
    ///
    /// Where `Foo` is a table and `bar` is an index over `Foo` using the `bar` field as foreign key.
    pub fn indexes(&self) -> D::IndexesWithOwner {
        (Arc::clone(&self.inner.store), self.owner).into()
    }
}

#[cfg(test)]
mod test {
    use std::sync::Arc;

    use crate::{KvErrorExt, store};

    store!(
        kvs: {
            Count(u64; OWNER),
            Shared(Arc<String>; OWNER),
            Label(&'static u64; OWNER),
            Boxed(Box<String>; OWNER),
        }
        tables: {
            Items(&'static str => String; OWNER),
            Counters(u32 => u64; OWNER),
        }
    );

    const OWNER: &str = "owner";
    const OTHER: &str = "other";

    #[test]
    fn get_returns_none_when_absent() {
        let store = KvStore::new();
        assert!(store.Count.get(OWNER).is_none());
    }

    #[test]
    fn get_returns_value_after_insert() {
        let store = KvStore::new();
        store.Count.insert(OWNER, 42);
        assert_eq!(store.Count.get(OWNER), Some(42));
    }

    #[test]
    fn get_ref_singleton() {
        static STATIC_LABEL: u64 = 99;
        let store = KvStore::new();
        store.Label.insert(OWNER, &STATIC_LABEL);
        assert_eq!(store.Label.get(OWNER), Some(&99));
    }

    #[test]
    fn with_returns_none_and_does_not_call_f_when_absent() {
        let store = KvStore::new();
        let mut called = false;
        let result = store.Count.with(OWNER, |_| {
            called = true;
        });
        assert!(result.is_none());
        assert!(!called);
    }

    #[test]
    fn with_returns_result_of_f() {
        let store = KvStore::new();
        store.Count.insert(OWNER, 5);
        assert_eq!(store.Count.with(OWNER, |v| v * 2), Some(10));
    }

    #[test]
    fn get_arc_singleton_shares_allocation() {
        let store = KvStore::new();
        let arc = Arc::new("hello".to_owned());
        store.Shared.insert(OWNER, arc.clone());
        let got = store.Shared.get(OWNER).unwrap();
        assert_eq!(*got, "hello");
        // `get` clones the `Arc` rather than the pointee.
        assert!(Arc::ptr_eq(&arc, &got));
    }

    #[test]
    fn with_mut_returns_none_and_does_not_call_f_when_absent() {
        let store = KvStore::new();
        let mut called = false;
        let result = store.Count.with_mut(OWNER, |_| {
            called = true;
        });
        assert!(result.is_none());
        assert!(!called);
    }

    #[test]
    fn with_mut_does_not_insert_when_absent() {
        let store = KvStore::new();
        store.Count.with_mut(OWNER, |v| *v = 7);
        assert!(store.Count.get(OWNER).is_none());
    }

    #[test]
    fn with_mut_passes_current_value() {
        let store = KvStore::new();
        store.Count.insert(OWNER, 5);
        let mut seen = None;
        store.Count.with_mut(OWNER, |v| seen = Some(*v));
        assert_eq!(seen, Some(5));
    }

    #[test]
    fn with_mut_returns_result_of_f() {
        let store = KvStore::new();
        store.Count.insert(OWNER, 5);
        assert_eq!(store.Count.with_mut(OWNER, |v| *v * 2), Some(10));
    }

    #[test]
    fn with_mut_mutates_existing_value() {
        let store = KvStore::new();
        store.Count.insert(OWNER, 5);
        store.Count.with_mut(OWNER, |v| *v *= 2);
        assert_eq!(store.Count.get(OWNER), Some(10));
    }

    #[test]
    fn with_mut_sees_previous_with_mut() {
        let store = KvStore::new();
        store.Count.insert(OWNER, 0);
        store.Count.with_mut(OWNER, |v| *v += 1);
        store.Count.with_mut(OWNER, |v| *v += 1);
        store.Count.with_mut(OWNER, |v| *v += 1);
        assert_eq!(store.Count.get(OWNER), Some(3));
    }

    #[test]
    fn with_mut_returns_none_after_remove() {
        let store = KvStore::new();
        store.Count.insert(OWNER, 5);
        store.Count.remove(OWNER);
        let mut called = false;
        let result = store.Count.with_mut(OWNER, |_| called = true);
        assert!(result.is_none());
        assert!(!called);
        assert!(store.Count.get(OWNER).is_none());
    }

    #[test]
    fn with_mut_box_singleton() {
        let store = KvStore::new();
        store.Boxed.insert(OWNER, Box::new("hello".to_owned()));
        store.Boxed.with_mut(OWNER, |v| v.push('!'));
        assert_eq!(store.Boxed.get(OWNER), Some(Box::new("hello!".to_owned())));
    }

    #[test]
    fn with_mut_arc_singleton() {
        let store = KvStore::new();
        store.Shared.insert(OWNER, Arc::new("hello".to_owned()));
        store
            .Shared
            .with_mut(OWNER, |v| *v = Arc::new(format!("{v}!")));
        assert_eq!(
            store.Shared.get(OWNER).as_deref(),
            Some(&"hello!".to_owned())
        );
    }

    #[test]
    fn with_mut_ref_singleton() {
        static OLD_LABEL: u64 = 1;
        static NEW_LABEL: u64 = 2;
        let store = KvStore::new();
        store.Label.insert(OWNER, &OLD_LABEL);
        store.Label.with_mut(OWNER, |v| {
            assert_eq!(**v, 1);
            *v = &NEW_LABEL;
        });
        assert_eq!(store.Label.get(OWNER), Some(&2));
    }

    #[test]
    #[cfg_attr(debug_assertions, should_panic(expected = "Ownership violation"))]
    fn with_mut_wrong_owner_panics() {
        let store = KvStore::new();
        store.Count.insert(OWNER, 1);
        store.Count.with_mut(OTHER, |v| *v = 2);
    }

    #[test]
    fn remove_makes_entry_absent() {
        let store = KvStore::new();
        store.Count.insert(OWNER, 1);
        store.Count.remove(OWNER);
        assert!(store.Count.get(OWNER).is_none());
    }

    #[test]
    #[cfg_attr(debug_assertions, should_panic(expected = "Ownership violation"))]
    fn singleton_insert_wrong_owner_panics() {
        let store = KvStore::new();
        store.Count.insert(OWNER, 1);
        store.Count.insert(OTHER, 2);
    }

    #[test]
    #[cfg_attr(debug_assertions, should_panic(expected = "Ownership violation"))]
    fn singleton_remove_wrong_owner_panics() {
        let store = KvStore::new();
        store.Count.insert(OWNER, 1);
        store.Count.remove(OTHER);
    }

    #[test]
    fn table_get_returns_none_when_absent() {
        let store = KvStore::new();
        assert!(store.Items.get(OWNER, "missing").is_none());
    }

    #[test]
    fn table_get_returns_value_after_insert() {
        let store = KvStore::new();
        store.Items.insert(OWNER, "k", "val".to_owned());
        assert_eq!(store.Items.get(OWNER, "k"), Some("val".to_owned()));
    }

    #[test]
    fn table_get_with_borrow_type() {
        let store = KvStore::new();
        store.Counters.insert(OWNER, 42u32, 100u64);
        assert_eq!(store.Counters.get(OWNER, &42u32), Some(100u64));
    }

    #[test]
    fn table_with_returns_none_and_does_not_call_f_when_absent() {
        let store = KvStore::new();
        let mut called = false;
        let result = store.Items.with(OWNER, "missing", |_| {
            called = true;
        });
        assert!(result.is_none());
        assert!(!called);
    }

    #[test]
    fn table_with_returns_some_after_insert() {
        let store = KvStore::new();
        store.Items.insert(OWNER, "k", "val".to_owned());
        assert_eq!(store.Items.with(OWNER, "k", |s| s.len()), Some(3));
    }

    #[test]
    fn table_mutate_returns_none_when_absent() {
        let store = KvStore::new();
        assert!(
            store
                .Items
                .with_mut(OWNER, &"missing", |v| v.len())
                .is_none()
        );
    }

    #[test]
    fn table_mutate_modifies_value() {
        let store = KvStore::new();
        store.Items.insert(OWNER, "k", "hello".to_owned());
        store.Items.with_mut(OWNER, &"k", |v| v.push('!')).unwrap();
        assert_eq!(store.Items.get(OWNER, "k"), Some("hello!".to_owned()));
    }

    #[test]
    fn table_remove_makes_get_return_none() {
        let store = KvStore::new();
        store.Items.insert(OWNER, "k", "v".to_owned());
        store.Items.remove(OWNER, &"k");
        assert!(store.Items.get(OWNER, "k").is_none());
    }

    #[test]
    fn table_clear_removes_all_rows() {
        let store = KvStore::new();
        let table = &store.Items;
        table.insert(OWNER, "a", "alpha".to_owned());
        table.insert(OWNER, "b", "beta".to_owned());
        table.insert(OWNER, "c", "gamma".to_owned());
        table.clear(OWNER);
        assert!(table.is_empty());
    }

    #[test]
    fn table_is_empty_on_fresh_store() {
        let store = KvStore::new();
        assert!(store.Items.is_empty());
    }

    #[test]
    fn table_len_zero_on_fresh_store() {
        let store = KvStore::new();
        assert_eq!(store.Items.len(), 0);
    }

    #[test]
    fn table_len_increases_with_inserts() {
        let store = KvStore::new();
        let table = &store.Items;
        table.insert(OWNER, "a", "alpha".to_owned());
        table.insert(OWNER, "b", "beta".to_owned());
        table.insert(OWNER, "c", "gamma".to_owned());
        assert_eq!(table.len(), 3);
    }

    #[test]
    fn table_len_decreases_after_remove() {
        let store = KvStore::new();
        let table = &store.Items;
        table.insert(OWNER, "a", "alpha".to_owned());
        table.insert(OWNER, "b", "beta".to_owned());
        table.remove(OWNER, &"a");
        assert_eq!(table.len(), 1);
    }

    #[test]
    fn table_is_empty_false_after_insert() {
        let store = KvStore::new();
        store.Items.insert(OWNER, "k", "v".to_owned());
        assert!(!store.Items.is_empty());
    }

    #[test]
    fn table_iter_empty_on_fresh_store() {
        let store = KvStore::new();
        let table = &store.Items;
        let count = table.with_iter(OWNER, |i| i.count());
        assert_eq!(count, 0);
    }

    #[test]
    fn table_iter_yields_all_rows() {
        let store = KvStore::new();
        let table = &store.Items;
        table.insert(OWNER, "a", "alpha".to_owned());
        table.insert(OWNER, "b", "beta".to_owned());
        let mut items: Vec<_> =
            table.with_iter(OWNER, |i| i.map(|(k, v)| (*k, v.clone())).collect());
        items.sort();
        assert_eq!(
            items,
            vec![("a", "alpha".to_owned()), ("b", "beta".to_owned())]
        );
    }

    #[test]
    fn table_iter_reflects_mutations() {
        let store = KvStore::new();
        let table = &store.Items;
        table.insert(OWNER, "k", "v1".to_owned());
        table
            .with_mut(OWNER, &"k", |v| {
                v.clear();
                v.push_str("v2");
            })
            .unwrap();
        let items: Vec<_> = table.with_iter(OWNER, |i| i.map(|(k, v)| (*k, v.clone())).collect());
        assert_eq!(items, vec![("k", "v2".to_owned())]);
    }

    #[test]
    fn table_with_iter_mut_modifies_values() {
        let store = KvStore::new();
        let table = &store.Items;
        table.insert(OWNER, "k", "hello".to_owned());
        table
            .with_iter_mut(OWNER, |i| i.next().unwrap().1.push('!'))
            .unwrap();
        assert_eq!(table.get(OWNER, "k"), Some("hello!".to_owned()));
    }

    #[test]
    fn table_with_iter_mut_empty_yields_none() {
        let store = KvStore::new();
        let table = &store.Items;
        let count = table.with_iter_mut(OWNER, |i| i.count()).unwrap();
        assert_eq!(count, 0);
    }

    #[test]
    fn table_with_iter_mut_visits_all_rows() {
        let store = KvStore::new();
        let table = &store.Items;
        table.insert(OWNER, "a", "x".to_owned());
        table.insert(OWNER, "b", "y".to_owned());
        table.insert(OWNER, "c", "z".to_owned());
        table
            .with_iter_mut(OWNER, |i| {
                for (_, v) in i {
                    v.push('!');
                }
            })
            .unwrap();
        assert_eq!(table.get(OWNER, "a"), Some("x!".to_owned()));
        assert_eq!(table.get(OWNER, "b"), Some("y!".to_owned()));
        assert_eq!(table.get(OWNER, "c"), Some("z!".to_owned()));
    }

    #[test]
    fn table_iter_keys_cloned_empty() {
        let store = KvStore::new();
        let table = &store.Items;
        let keys: Vec<&str> = table.with_keys(OWNER, |i| i.copied().collect());
        assert!(keys.is_empty());
    }

    #[test]
    fn table_iter_keys_cloned_yields_all_keys() {
        let store = KvStore::new();
        let table = &store.Items;
        table.insert(OWNER, "a", "alpha".to_owned());
        table.insert(OWNER, "b", "beta".to_owned());
        let mut keys: Vec<_> = table.with_keys(OWNER, |i| i.copied().collect());
        keys.sort();
        assert_eq!(keys, vec!["a", "b"]);
    }

    #[test]
    fn table_iter_values_cloned_empty() {
        let store = KvStore::new();
        let table = &store.Items;
        let values: Vec<String> = table.with_values(OWNER, |i| i.cloned().collect());
        assert!(values.is_empty());
    }

    #[test]
    fn table_iter_values_cloned_yields_all_values() {
        let store = KvStore::new();
        let table = &store.Items;
        table.insert(OWNER, "a", "alpha".to_owned());
        table.insert(OWNER, "b", "beta".to_owned());
        let mut values: Vec<_> = table.with_values(OWNER, |i| i.cloned().collect());
        values.sort();
        assert_eq!(values, vec!["alpha", "beta"]);
    }

    #[test]
    #[cfg_attr(debug_assertions, should_panic(expected = "Ownership violation"))]
    fn table_insert_wrong_owner_panics() {
        let store = KvStore::new();
        store.Items.insert(OTHER, "k", "v".to_owned());
    }

    #[test]
    #[cfg_attr(debug_assertions, should_panic(expected = "Ownership violation"))]
    fn table_mutate_wrong_owner_panics() {
        let store = KvStore::new();
        store.Items.with_mut(OTHER, &"k", |v| v.len()).unwrap_err();
    }

    #[test]
    #[cfg_attr(debug_assertions, should_panic(expected = "Ownership violation"))]
    fn table_remove_wrong_owner_panics() {
        let store = KvStore::new();
        store.Items.remove(OTHER, &"k");
    }

    #[test]
    #[cfg_attr(debug_assertions, should_panic(expected = "Ownership violation"))]
    fn table_clear_wrong_owner_panics() {
        let store = KvStore::new();
        store.Items.clear(OTHER);
    }

    #[test]
    fn with_owner_singleton_round_trip() {
        let store = KvStore::new();
        let owned = store.with_owner(OWNER);

        owned.Count.insert(5);
        assert_eq!(owned.Count.get(), Some(5));
        assert_eq!(owned.Count.with(|v| v * 2), Some(10));
        assert_eq!(owned.Count.with_mut(|v| *v += 1), Some(()));
        assert_eq!(owned.Count.get(), Some(6));

        owned.Count.remove();
        assert!(owned.Count.get().is_none());
    }

    #[test]
    fn with_owner_table_round_trip() {
        let store = KvStore::new();
        let owned = store.with_owner(OWNER);

        owned.Items.insert("a", "alpha".to_owned());
        owned.Items.insert("b", "beta".to_owned());
        assert_eq!(owned.Items.get("a"), Some("alpha".to_owned()));
        assert_eq!(owned.Items.with("a", |v| v.len()), Some(5));
        assert_eq!(owned.Items.len(), 2);
        assert!(!owned.Items.is_empty());

        owned.Items.with_mut(&"a", |v| v.push('!')).unwrap();
        assert_eq!(owned.Items.get("a"), Some("alpha!".to_owned()));

        let mut keys: Vec<_> = owned.Items.with_keys(|i| i.copied().collect());
        keys.sort();
        assert_eq!(keys, vec!["a", "b"]);
        assert_eq!(owned.Items.with_iter(|i| i.count()), 2);
        assert_eq!(owned.Items.with_values(|i| i.count()), 2);

        owned
            .Items
            .with_iter_mut(|i| {
                for (_, v) in i {
                    v.push('?');
                }
            })
            .unwrap();
        assert_eq!(owned.Items.get("b"), Some("beta?".to_owned()));

        owned.Items.remove(&"a");
        assert_eq!(owned.Items.len(), 1);
        owned.Items.clear();
        assert!(owned.Items.is_empty());
    }

    #[test]
    fn with_owner_writes_visible_to_the_store() {
        let store = KvStore::new();
        {
            let owned = store.with_owner(OWNER);
            owned.Count.insert(7);
            owned.Items.insert("k", "v".to_owned());
        }
        assert_eq!(store.Count.get(OWNER), Some(7));
        assert_eq!(store.Items.get(OWNER, "k"), Some("v".to_owned()));
    }

    #[test]
    fn with_owner_transaction_uses_the_owner() {
        let store = KvStore::new();
        let owned = store.with_owner(OWNER);

        let mut txn = owned.begin_transaction();
        txn.Count.insert(1);
        txn.Items.insert("k", "v".to_owned());
        txn.commit().unwrap();

        assert_eq!(owned.Count.get(), Some(1));

        let txn = owned.begin_ro_transaction();
        assert_eq!(txn.Items.get("k"), Some("v".to_owned()));
    }

    #[test]
    #[cfg_attr(debug_assertions, should_panic(expected = "Ownership violation"))]
    fn with_owner_wrong_owner_panics() {
        let store = KvStore::new();
        store.Count.insert(OWNER, 1);
        store.with_owner(OTHER).Count.insert(2);
    }
}
