name: nix

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    name: nix flake check
    runs-on: linux-x86_64-16cpu
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: cachix/install-nix-action@ab739621df7a23f52766f9ccc97f38da6b7af14f # v31.10.5
      - run: nix flake check -L

  build:
    strategy:
      matrix:
        include:
          - target: x86_64-linux
            runner: linux-x86_64-16cpu
          - target: aarch64-linux
            runner: linux-arm64-16cpu

    name: nix build ${{ matrix.target }}
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: cachix/install-nix-action@ab739621df7a23f52766f9ccc97f38da6b7af14f # v31.10.5

      - name: nix build
        run: |-
          exec nix build -L .
